### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by AbelCode1** [brblacky/lavamusic#103]
![8A4A5DF2-C076-4AE0-97AD-4DD9B71972C4](https://user-images.githubusercontent.com/90580222/150698282-901aac1d-d053-4646-bbe4-231eabaf856e.jpeg)

**Comment by SpaceLeft** [comment]
which host you used?

**Comment by AbelCode1** [comment]
> which host you used?

pterodactyl

**Comment by RennJs** [comment]
How is the disk space only 50MB?
It must be 400mb or more

**Comment by SpaceLeft** [comment]
> > which host you used?
> 
> pterodactyl

give me the link of host let me test search is working with me fine.

**Comment by AbelCode1** [comment]
> > > which host you used?
> > 
> > 
> > pterodactyl
> 
> give me the link of host let me test search is working with me fine.

https://panel.projectavocados.com/

**Comment by AbelCode1** [comment]
> How is the disk only 50MB? It must be 400mb or more

thats what i used
