### ISSUE TITLE
Slash Command Error

### ISSUE THREAD

**Issue by sandarutharuneth** [brblacky/lavamusic#118]
The bot doesn't respond to the Slash Commands [ /play ]

 **It only gives this message**

- [+] You must be in the same channel as @channelname

Bot only works with normal prefix commands. When you connect the bot with normal prefix command to the vc, then you can use slash commands normally. I think the error with connecting to the vc with slash commands. Please fix this.

**Comment by AkAbhijit** [comment]
> The bot doesn't respond to the Slash Commands [ /play ]
> 
> **It only gives this message**
> 
> * [+] You must be in the same channel as @channelname
> 
> Bot only works with normal prefix commands. When you connect the bot with normal prefix command to the vc, then you can use slash commands normally. I think the error with connecting to the vc with slash commands. Please fix this.

https://github.com/brblacky/lavamusic/commit/ff31d9224277070f383ff86b4e3bb31787e584bf

**Comment by AkAbhijit** [comment]
https://github.com/brblacky/lavamusic/commit/ff31d9224277070f383ff86b4e3bb31787e584bf
