### ISSUE TITLE
Node randomly disconnects and reconnects

### ISSUE THREAD

**Issue by Tibor309** [brblacky/lavamusic#125]
When the bot is running, after some time, the node disconnects and reconnects, causing the currently playing song to stop. I have to manually disconnect and reconnect the bot to the voice channel to fix it.

```
[26-02-2022 01:25:22]: [WARN] Node "disbotlistlavalink.ml" disconnect because [object Object].
[26-02-2022 01:25:52]: [LOG] Node "disbotlistlavalink.ml" reconnected.
[26-02-2022 01:25:52]: [READY] Node "disbotlistlavalink.ml" connected.
```
I didn't found any help to fix this, so this is my last option.
I'm running the bot on [replit](https://replit.com/@Tibor309/splash-music) with node.js v12.22.6 and an express server to keep the bot alive. I removed loading the slash commands, because i don't need them. Heres the full [log](https://github.com/brblacky/lavamusic/files/8146737/log.txt).

**Comment by TEDDY6969** [comment]
Please use another Lavalink!!
As many players running on the same Lavalink this of error can be seen. I suggest you to make your own private lava with the blacky's Lavalink server project.

**Comment by Tibor309** [comment]
I tried, but i still have the same issue. I looked for one on [this](https://lavalink.darrennathanael.com/SSL/lavalink-with-ssl/) website. And currently i can't make my own.

```
[27-02-2022 12:21:44]: [WARN] Node "www.lavalink-priyam.ml" disconnect because [object Object].
[27-02-2022 12:22:14]: [LOG] Node "www.lavalink-priyam.ml" reconnected.
[27-02-2022 12:22:15]: [READY] Node "www.lavalink-priyam.ml" connected.
```

**Comment by TEDDY6969** [comment]
Hey there,

I suggest you to use latest version of lavamusic that is v1.0.9 and if you already using that then kindly join our support server for the Lavalink server that actually works or you can dm me at ❀SUNSHİNE❀#1359  for further help.

Thanks

**Comment by MJGaming1532** [comment]
> I tried, but i still have the same issue. I looked for one on [this](https://lavalink.darrennathanael.com/SSL/lavalink-with-ssl/) website. And currently i can't make my own.
> 
> ```
> [27-02-2022 12:21:44]: [WARN] Node "www.lavalink-priyam.ml" disconnect because [object Object].
> [27-02-2022 12:22:14]: [LOG] Node "www.lavalink-priyam.ml" reconnected.
> [27-02-2022 12:22:15]: [READY] Node "www.lavalink-priyam.ml" connected.
> ```

please use no ssl lavalink and make the secure from "true" to "false"

**Comment by Tibor309** [comment]
So i made my own lavalink server, and that kinda solved it. I still get the same errors, but now it doesn't disconnects while music is playing, or anyone using it.
