### ISSUE TITLE
247 Mode isn't Working 

### ISSUE THREAD

**Issue by Rubul1** [brblacky/lavamusic#132]
247 Mode Isn't working when I on it

**Comment by RennJs** [comment]
> yes me too, on the voice channel it works, but on the stage channel it didn't work (no sound).

It works when you set the bot to speak

**Comment by irzikhairunuzulan** [comment]
Thanks, It Works.

**Comment by Rodin1a** [comment]
How to speak? Even if you ask me to speak, if I leave on the way, it will be suspended.

**Comment by Rodin1a** [comment]
> Thanks, It Works.

How did you solve it?

**Comment by TEDDY6969** [comment]
> set bot to speak:
This mean play some long stream i.e non stop music, game stream and that will help it to stay 247 in vc

**Comment by Rodin1a** [comment]
> > set bot to speak:
> > This mean play some long stream i.e non stop music, game stream and that will help it to stay 247 in vc

Thanks !!!

**Comment by Rodin1a** [comment]
> > set bot to speak:
> > This mean play some long stream i.e non stop music, game stream and that will help it to stay 247 in vc

There was an error when I played the real-time stream. How did you solve this problem?
Or is it a problem with my lavalink server?

**Comment by TEDDY6969** [comment]
Sometimes tracks face some error i.e. socket is not longer valid or smth like that so it's not a big deal try playing smth else 
I.e rock live stream
https://youtu.be/5X18D-EbjUc

**Comment by LucasB25** [comment]
@brblacky You can close this one!
