### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by REMOOO** [brblacky/lavamusic#133]
When i run the bot this error appear
![Capture](https://user-images.githubusercontent.com/13511097/156911578-206e0004-2c1e-4c13-9b54-a76ac2b2b421.PNG)

**Comment by Rubul1** [comment]
It's is nothing like problem bro

**Comment by AlexanderOFGR** [comment]
I have this issue too! Is there anybody that fixed it somehow?
![image](https://user-images.githubusercontent.com/58230188/161395291-a1e73c3a-3795-4ec0-9156-36c6f2ec18e1.png)

**Comment by RedBuls81** [comment]
I have this issue too! Is there anybody that fixed it somehow?

**Comment by AdityaOP2008** [comment]
This isn't a issue with the codes.
It's a no perms note.
Bot don't have application commands permissions.
