### ISSUE TITLE
When the bot disconnected manually it will broken

### ISSUE THREAD

**Issue by RennJs** [brblacky/lavamusic#138]
**Detail Explanation**
When you disconnect the bot manually from the VC and use "play" command it will tell us to join the previous VC

**To Reproduce**
- Use "leave" command first
- If already occurs use,"join" command then "play" command 

**Screenshots**
![Screenshot_20220317-205914_Discord-Beta](https://user-images.githubusercontent.com/98434771/159405306-fd449869-43ed-444f-a8e9-265b1295a55b.jpg)

 - Device: Android And PC

**Comment by brblacky** [comment]
@
