### ISSUE TITLE
Bot doesn't search nor play songs by name, only by direct link

### ISSUE THREAD

**Issue by panda4k** [brblacky/lavamusic#144]
**Describe the bug**
Bot joins and leaves the voice channel when asked to play a song by name. Bot doesn't find any songs when asked to search.

**To Reproduce**
1. Make sure the bot is not in a voice channel,
2. Play a song by name (play Never gonna give you up),
3. Bot joins and quits,
4. Error in console (bellow).

**Expected behavior**
Bot should say that it is searching for the song, that it found it, and started playing it. (It also fails to search (stays at "Searching <songname> and never moves on"))

**Screenshots**
Screenshot of the error thrown in the console [here](https://imgur.com/yrx1eRq).

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Discord app, not browser

**Additional context**
Bot is running on latest java 17 on Ubuntu 20.04, NPM 8.9.0. It was working fine up until a week or so ago when I was doing my regular system updates and upgrades (maybe one of the above requirements got updated and started causing this or similar.)
Here is the text friendly version of the error code:

`TypeError: [(intermediate value)].setColor is not a function
    at Object.execute (/root/newmusicbot/src/commands/Music/play.js:53:68)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by unitictv** [comment]
Replace line 53 with this:
`return message.channel.send({ embeds: [new MessageEmbed().setTimestamp().setColor(client.embedColor).setDescription(`No matches found for - ${search}`)]});`

The **]** is in the wrong place in the original code.

**Comment by unitictv** [comment]
As for the search, I haven't found a solution yet, still only plays from YouTube links.

**Comment by panda4k** [comment]
> Replace line 53 with this: `return message.channel.send({ embeds: [new MessageEmbed().setTimestamp().setColor(client.embedColor).setDescription(`No matches found for - ${search}`)]});`
> 
> The **]** is in the wrong place in the original code.

That raises another error, probably something similar as earlier, so I replaced it with this:
`return message.channel.send({ embeds: [new MessageEmbed().setColor(client.embedColor).setTimestamp().setDescription("No matches found...")] });`

As for the search, It used to work just fine, it was searching youtube and offering 5 buttons to choose the top 5 results to play, upon clicking one it would play/add to queue. I suppose we gotta wait for more clarification to this. Either way I hope this helps someone else.

**Comment by panda4k** [comment]
Accidentally closed it..
