### ISSUE TITLE
Automatically disconnect

### ISSUE THREAD

**Issue by SypherRed** [brblacky/lavamusic#146]
**Is your feature request related to a problem? Please describe.**
A similar issue has been opened and closes before. https://github.com/brblacky/lavamusic/issues/105

**Describe the solution you'd like**
Let the Bot disconnect after a set time (either with command setup or config) if either the channel is empty, and/or no music is playing.

**Comment by LucasB25** [comment]
@SypherRed Does the problem still exist?

**Comment by SypherRed** [comment]
Hey there, thank you for your response.
Unfortunately, I'm currently not able to check anything due to not being at home.

Anyways, this was not meant to be a issue, it was meant to be a suggestion/improvement.

**Comment by LucasB25** [comment]
I put your suggestion on hold for a return
