### ISSUE TITLE
Unable to stop song using button interaction

### ISSUE THREAD

**Issue by SypherRed** [brblacky/lavamusic#148]
**Describe the bug**
Bot is unable to register "Stop" Button

**To Reproduce**
1. Start a music
2. Click on the "Stop" Button (second from left-side)
3. See error as "This interaction failed" and console

**Expected behavior**
Stopping the current playing song/music

**Error Message**
`TypeError: NowPlaying.createMessageComponentCollector is not a function
at module.exports (C:\Users\USER\Desktop\lavamusic-1.1.0v\src\events\Lavalink\trackStart.js:39:32)
at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Screenshots**
[Console Error Output](https://i.imgur.com/LOFMf33.png)

**Comment by brblacky** [comment]
Use letest update

**Comment by SypherRed** [comment]
> Use letest update

Will try it once I have time and then comment back.

Thanks for your reply.

**Comment by LucasB25** [comment]
@brblacky I see the concern seems to have been resolved, so you can close
