### ISSUE TITLE
Cant load more than one track

### ISSUE THREAD

**Issue by MasterModz1243** [brblacky/lavamusic#156]
**Describe the bug**
When i start the bot with a song and then request another one or it finishes and request another one it throws this error and i cant to seem to find the source

**To Reproduce**
1: have the bot loaded
2:request a song for example After dark
3: wait for song to end and request another one/request another one
4: Look at console and see this 
DiscordAPIError: Invalid Form Body
embeds[0].description: This field is required
    at RequestHandler.execute (/home/runner/ReplMusicv2/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/ReplMusicv2/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/home/runner/ReplMusicv2/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15) {
  method: 'post',
  path: '/channels/985612381625413642/messages',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [Array],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/88443296/173920166-d8615623-7ca7-45e1-84d2-8ae13ee84e57.png)
![image](https://user-images.githubusercontent.com/88443296/173920218-33732bcd-12b7-47eb-89ed-bfcceacba92c.png)

**Desktop (please complete the following information):**
 - OS: Win 11,pro
 - Browser Firefox

**Additional context**
Feel free to contact me on discord if i dont see the response on here (sorry if i dont) 𝑱𝒂𝒎 𝑹𝒐𝒍𝒚𝒑𝒐𝒍𝒚#1216

**Comment by LucasB25** [comment]
You are using which version of the github?

**Comment by MasterModz1243** [comment]
im not running it on github im running it on Replit

**Comment by LucasB25** [comment]
No you did not understand, what is the version of the repo lavaMusic you use. 
_This one where we talk_

**Comment by MasterModz1243** [comment]
I believe i am running the latest one because i only intalled it like a week ago

**Comment by LucasB25** [comment]
After checking, you are not on the latest version, but a version with some problems.
So I’ll let you update

**Comment by Rstacx** [comment]
you are not on the latest version, but a version with some problems.
