### ISSUE TITLE
Error Run index.js

### ISSUE THREAD

**Issue by TuyAnCong** [brblacky/lavamusic#160]
**Describe the bug**
A clear and concise description of what the bug is Run!

**To Reproduce**
1. Go to lavamusic on replit
2. Click on Console
3. Scroll down

**Expected behavior**
Please help
```
Error: cannot find module 'node:event'
```
**Screenshots**
![Screenshot_20220620-151044_Chrome](https://user-images.githubusercontent.com/97296405/174556685-48b03aaf-3268-4631-9769-3fb90f6b04bf.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung 
 - OS: Android8.1
 - Browser: Chrome
 - Version: 27

**Additional context**
Please help, I make bot "RyteTeam" to I not time it

**Comment by LucasB25** [comment]
Hello, what version of node are you using?

**Comment by TuyAnCong** [comment]
^16

**Comment by LucasB25** [comment]
yes but 16. how much?

**Comment by brblacky** [comment]
Update node version

**Comment by TuyAnCong** [comment]
thank, but I not time, sorry to for open issue
