### ISSUE TITLE
Add command and add cooldown

### ISSUE THREAD

**Issue by hatry4** [brblacky/lavamusic#161]
I have a snippet for reset prefix command and Can i rquest to add commmand cooldown events so the command wont get abused by users.

**Comment by LucasB25** [comment]
@ShibaInu0413 There’s this proposal that’s really not stupid

**Comment by LucasB25** [comment]
> > @ShibaInu0413 There’s this proposal that’s really not stupid
> 
> It's a good proposal. There's an example in the discord.js guide. I don't think it's difficult. It just takes time.

Then I don’t have much time on my side so if you want to look into it

**Comment by ShibaInu0413** [comment]
> Then I don’t have much time on my side so if you want to look into it

I think multilingual systems are more interesting to me

**Comment by ShibaInu0413** [comment]
冷卻系統不是那麼的重要 他只是避免了濫用

**Comment by ShibaInu0413** [comment]
The cooling system is not that important, he just avoids abuse

**Comment by LucasB25** [comment]
as you say, if it’s not very long to do, it’s better to do it with

**Comment by ShibaInu0413** [comment]
> as you say, if it’s not very long to do, it’s better to do it with

I'll fix this when I have time.  I have to go to work.

**Comment by ShibaInu0413** [comment]
https://v12.discordjs.guide/command-handling/adding-features.html#cooldowns

This is the method used in the guide

**Comment by LucasB25** [comment]
you to send the one of the v12

**Comment by ShibaInu0413** [comment]
> you to send the one of the v12

I know, but that doesn't stop us from using it

**Comment by ShibaInu0413** [comment]
@LucasB25 I want to write the cooldown settings in config.js what do you think

**Comment by ShibaInu0413** [comment]
This will cause Docker to not be able to change the cooldownType or time by itself

**Comment by LucasB25** [comment]
> This will cause Docker user to not be able to change the cooldownType or time by itself

generally cooldown its own to a command

**Comment by ShibaInu0413** [comment]
> > This will cause Docker user to not be able to change the cooldownType or time by itself
> 
> generally cooldown its own to a command

So you don't have to do it all?
