### ISSUE TITLE
Add Autocomplete slash play command

### ISSUE THREAD

**Issue by pasindu20** [brblacky/lavamusic#162]
![174233019-68084b8d-c4ea-423d-91b8-94ba798c53a9](https://user-images.githubusercontent.com/77439977/175952860-7e66b4d4-1baa-4170-ae64-389afa17451f.png)

Add autocomplete search command like soul music  and this also have yt search on autocomplete

https://discordjs.guide/interactions/autocomplete.html#enabling-autocomplete

**Comment by LucasB25** [comment]
It may be nice, but I disagree

**Comment by brblacky** [comment]
It is to load in bot
