### ISSUE TITLE
no voice channel

### ISSUE THREAD

**Issue by modee0011** [brblacky/lavamusic#163]
RangeError: No voice channel has been set.
    at Player.connect (/root/lava/node_modules/erela.js/dist/structures/Player.js:146:19)
    at Object.execute (/root/lava/commands/music/play.js:55:50)

 const { channel } = message.member.voice;

        var player = message.client.manager.get(message.guild.id);

        if(!args.length) return message.channel.send("*put name of song*")
         if (!player) {
            var player = message.client.manager.create({
                guild: message.guild.id,
                voiceChannel: channel.id,
                textChannel: message.channel.id,
                volume:  50,
                selfDeafen: true,
            });
        }

**Comment by modee0011** [comment]
I didn't understand what you mean exactly but every time I try to make a connection to the voice channel I get this error
in play command

**Comment by modee0011** [comment]
and join command
i use odl virson of bot but it was work

**Comment by LucasB25** [comment]
I can’t repeat your mistake
