### ISSUE TITLE
Features that may be optimized

### ISSUE THREAD

**Issue by ShibaInu0413** [brblacky/lavamusic#169]
1. Command `stop`
The current function of the `stop` command is too similar to the `clear` of other robots
I think we can rename him `clear`
Let `stop` and `leave` merge into `stop`

    By the way, the still button should do the same

2. Embed that appears when you start playing
I found that in the source code the trackStart event will change the button due to setup but their custom id is not the same but the function is the same
I suggest to use them the same custom id and do it in playerButtons event

3. Use <Message>.createMessageComponentCollector in trackStart
This is a bad idea
In the process I use when I use pause
As long as the song time is exceeded, the button will not work
Just like the previous question, I hope he can use the playerButtons event to operate

**Comment by LucasB25** [comment]
I didn’t fully understand
