### ISSUE TITLE
24/7?

### ISSUE THREAD

**Issue by GeoXTen** [brblacky/lavamusic#17]
how bot kept running on replit?

**Comment by hadif09** [comment]
Use uptimer bot

**Comment by GeoXTen** [comment]
> Use uptimer bot

how then?

**Comment by brblacky** [comment]
https://replit.com/talk/learn/Hosting-discordjs-bots-on-replit-Works-for-both-discordjs-and-Eris/11027

**Comment by GeoXTen** [comment]
> https://replit.com/talk/learn/Hosting-discordjs-bots-on-replit-Works-for-both-discordjs-and-Eris/11027

where i put ```conts``` in index.js / ready.js?
