### ISSUE TITLE
Error displaying the setup.js command (slash command and by prefix)

### ISSUE THREAD

**Issue by ZenoX-YT** [brblacky/lavamusic#214]
Hello support team, I just found a huge bug of the `setup.js` command (in slash command and by prefix). thank you and good evening.

https://user-images.githubusercontent.com/99297259/179821432-c4dfe5c4-5e97-4109-ab84-d6b43b921250.mp4

**Comment by LucasB25** [comment]
Give error

**Comment by ZenoX-YT** [comment]
Here is the error:
![image](https://user-images.githubusercontent.com/99297259/179824386-748d0383-99ca-445d-a06a-457cbefbc197.png)

**Comment by RTurkArmy** [comment]
i have the same error. also there was no setup information in the database.
![image](https://user-images.githubusercontent.com/70570676/179824637-76a80a60-c0a5-4f8a-b1fd-1fa1f6a59439.png)
