### ISSUE TITLE
Have Error In Clinet.js

### ISSUE THREAD

**Issue by rockerhemanth** [brblacky/lavamusic#222]
![Screenshot_20220721_191648](https://user-images.githubusercontent.com/99542221/180339702-4f4df34d-26a6-4165-87ea-1f40419ed1bc.jpg)
![Screenshot_20220720_214948](https://user-images.githubusercontent.com/99542221/180339717-c25f87e5-8528-45f9-acda-da8e9de82d51.jpg)

**Comment by parasop** [comment]
Update your node.js

**Comment by LucasB25** [comment]
you must be under node.js 16.16.0 preferably
