### ISSUE TITLE
Issue of `help` command in Slash command

### ISSUE THREAD

**Issue by ZenoX-YT** [brblacky/lavamusic#224]
I found an error typing `/help` in slash command

![bug](https://user-images.githubusercontent.com/99297259/180450349-df850566-6aae-49bf-a7da-e11c1902de29.png)

**Comment by ZenoX-YT** [comment]
![bug2](https://user-images.githubusercontent.com/99297259/180451081-dc885430-1624-48e0-b6ca-1d0d5617bbbc.png)

**Comment by LucasB25** [comment]
![image](https://user-images.githubusercontent.com/50886682/180452747-9d470cd0-faac-4db5-9e33-1ba86fbfd1ca.png)
waiting will be the only solution
