### ISSUE TITLE
Add a multi-language system

### ISSUE THREAD

**Issue by ZenoX-TV** [brblacky/lavamusic#227]
I propose for the future of the project to add a _multi-language_ system

**Comment by Legoman99573** [comment]
https://www.npmjs.com/package/translate looks promising.

Just have to make it where there is a system default and a command for server owners to swap the language around per guild, but the downsides is requiring a key for it to function and translations may be botched plus not knowing limitations of each service either. Would need excessive testing to recommend a service to use while still allowing people to still switch translation providers.

**Comment by NotAditya69** [comment]
multi-language will require all texts to be re-written in the i18 moderate form if you ready to do that then sure

**Comment by nfsmaniac** [comment]
> https://www.npmjs.com/package/translate looks promising.
> 
> Just have to make it where there is a system default and a command for server owners to swap the language around per guild, but the downsides is requiring a key for it to function and translations may be botched plus not knowing limitations of each service either. Would need excessive testing to recommend a service to use while still allowing people to still switch translation providers.

It can be utilized for some future /translate command, or to translate song lyrics.
But no machine translation of the bot's response messages, please.

**Comment by NotAditya69** [comment]
reopen this whenever you like, Since there's no one up for it we are sadly dropping this for now

**Comment by nfsmaniac** [comment]
I'm actually working on it right now, as a side-task to `/search` command redesign (as to incorporate the search from multiple sources). And because some strings sharing is starting to be both useful and called for since this point, multi-language support is just a little addition to the whole system.
