### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by pasindu20** [brblacky/lavamusic#231]
Bot is not joining the stage channel it joined but not go to speaker mode
we need to invite it manual fix this bug

**Comment by pasindu20** [comment]
> error please

No errors given

**Comment by pasindu20** [comment]
> error please

![image](https://user-images.githubusercontent.com/77439977/181923482-c0507a0e-3f3b-4b7f-aa5e-854d685a3dd2.png)
on main bot it not working either

**Comment by brblacky** [comment]
What not working

**Comment by pasindu20** [comment]
> What not working

Bot is not go to speaker mode i mean it only connect stage channel as a audience

**Comment by pasindu20** [comment]
> What not working

So basically if normal user join stage channel and play songs it not hearing because of bot is not speaker it will stay audience
this is major bug of play function

**Comment by LucasB25** [comment]
This bug concerns the bot Moe and the github lavaMusic?

**Comment by pasindu20** [comment]
> This bug concerns the bot Moe and the github lavaMusic?

Yes

**Comment by LucasB25** [comment]
it doesn’t answer the question

**Comment by pasindu20** [comment]
> it doesn’t answer the question

Both of it , why did i answer this much questions test it you will see the bug

**Comment by pasindu20** [comment]
Is this bug fix on next update ??

**Comment by LucasB25** [comment]
If you don’t give permission to talk to the bot it’s normal that he doesn’t make any music

**Comment by pasindu20** [comment]
> If you don’t give permission to talk to the bot it’s normal that he doesn’t make any music ![image](https://user-images.githubusercontent.com/50886682/182020563-52cda69e-723b-494e-ab9e-0c125cdbd9cc.png)

![image](https://user-images.githubusercontent.com/77439977/182021945-513d10fa-3c73-451b-8e4b-bdf16e003b9d.png)
bot have all perms it need aslo i found the issue on **voiceStateUpdate** event not working (if voice.size == 0) player pause right but it didn't pause 
i think voiceStateUpdate event not working that the issue here

**Comment by LucasB25** [comment]
He can have the necessary permissions if someone doesn’t give him permission to be in the chat zone he won’t go himself

**Comment by pasindu20** [comment]
> He can have the necessary permissions if someone doesn’t give him permission to be in the chat zone he won’t go himself
the actual issue is voiceStateUpdate evet not working 
if it get working all above issues are fixed
can you check it why is that voiceStateUpdate event not working??

**Comment by pasindu20** [comment]
contact me faster responce DJHammer#7246

**Comment by LucasB25** [comment]
![image](https://user-images.githubusercontent.com/50886682/182022746-e66fcbcf-45be-4b5a-9008-285d333923d5.png)
it works without any worries

**Comment by pasindu20** [comment]
> ![image](https://user-images.githubusercontent.com/50886682/182022746-e66fcbcf-45be-4b5a-9008-285d333923d5.png) it works without any worries

invite  of server

**Comment by LucasB25** [comment]
> invite of server or bot

what??

**Comment by pasindu20** [comment]
> > invite of server or bot
> 
> what??

invite of that bot so i can test it

**Comment by LucasB25** [comment]
I’m not here for advertising but to help, if you want the bot information all and in my profile

**Comment by brblacky** [comment]
> > error please
> 
> ![image](https://user-images.githubusercontent.com/77439977/181923482-c0507a0e-3f3b-4b7f-aa5e-854d685a3dd2.png) on main bot it not working either

Fixed in MoE
