### ISSUE TITLE
savequeue bug

### ISSUE THREAD

**Issue by PandaIN95** [brblacky/lavamusic#232]
save queue command removes existing songs from the playlist and adds the new songs into it it does not add new songs it just replaces old songs into new songs 

- Commit Hash:
- Node.js version: v16.16.0
- Operating system: Ubuntu 20.04

**Comment by LucasB25** [comment]
error please

**Comment by LucasB25** [comment]
> save queue command removes existing songs from the playlist and adds the new songs into it it does not add new songs it just replaces old songs into new songs

that's totally normal

**Comment by LucasB25** [comment]
it saves the playlist played and replaces the playlist you have chosen

**Comment by LucasB25** [comment]
no
