### ISSUE TITLE
Switch library

### ISSUE THREAD

**Issue by pasindu20** [brblacky/lavamusic#239]
I'm seen some bug on erela.js if bot start bot join vc and play music ram go up slowly and after 1 day it get more bigger and bigger
also erela.js kind a outof date so can you switch shoukaku or https://npmjs.com/poru this
i personality  test poru its better then shoukaku

**Comment by brblacky** [comment]
Poru is copy paste

**Comment by pasindu20** [comment]
> Poru is copy paste

Ya but it fix the memory issue on erela

**Comment by brblacky** [comment]
What type of memory ?

**Comment by pasindu20** [comment]
On this repo bot start and play the song on vc the hep memory will go slowly up 
Ilke on start it get 50mb after 1 hour it go to 60-80mb after 1 day online it get 200-300mb memory use (ram)
 But on poru bot start like 50 but after 1 hour it gose to 50-58mb after 1 day online it gose 70-80mb that what i mean if bot is on 1000+ server this erela use tons of ram to it

I have bot with 13k server  1 day online it gose to 5gb ram use 
But 12k server other bot use shoukaku it only gose 800-1000mb
On shoukaku kind a similer to poru

**Comment by pasindu20** [comment]
I also test this https://github.com/brblacky/WaveMusic  this is good but npm package got update so update it to newer  version

**Comment by brblacky** [comment]
> ~On this repo bot start and play the song on vc the hep memory will go slowly up Ilke on start it get 50mb after 1 hour it go to 60-80mb after 1 day online it get 200-300mb memory use (ram) But on poru bot start like 50 but after 1 hour it gose to 50-58mb after 1 day online it gose 70-80mb that what i mean if bot is on 1000+ server erela use tons of ram to it~ Nvm poru has that memory issue too but shoukaku don't have that

I personally use erela.js i don't get any problem with this
