### ISSUE TITLE
Please..

### ISSUE THREAD

**Issue by TechiePotato** [brblacky/lavamusic#243]
Hey, please convert erela to shoukaku cuz the erela is no more supported.
And pls add filter external like we have to type (prefix)8d to add 8d filter.

**Comment by TechiePotato** [comment]
Hey, please convert erela to shoukaku cuz the erela is no more supported.
And pls add filter external like we have to type (prefix)8d to add 8d filter.

**Comment by TechiePotato** [comment]
Hey, please convert erela to shoukaku cuz the erela is no more supported.
And pls add filter external like we have to type (prefix)8d to add 8d filter.

**Comment by pasindu20** [comment]
Yes i also asked the erela.js support they said erela.js is Discord's terms of service so erela.js is officially not getting any updates and other things **erela.js was abandoned** so change shoukaku or https://github.com/brblacky/WaveMusic update wavemusic repo
also it use `kazagumo`- more easy shoukaku used wrapper update that it had new updates comes
*so i say erela.js is no longer continued or getting any more updates so that why this need to be changed*

**Comment by pasindu20** [comment]
> Yes i also asked the erela.js support they said erela.js is braking Discord's terms of service so erela.js is officially not getting any updates and other things **erela.js was abandoned** so change shoukaku or https://github.com/brblacky/WaveMusic update wavemusic repo also it use `kazagumo`- more easy shoukaku used wrapper update that it had new updates comes _so i say erela.js is no longer continued or getting any more updates so that why this need to be changed_

resuggest it make to updating library like poru

**Comment by pasindu20** [comment]
> > Yes i also asked the erela.js support they said erela.js is braking Discord's terms of service so erela.js is officially not getting any updates and other things **erela.js was abandoned** so change shoukaku or https://github.com/brblacky/WaveMusic update wavemusic repo also it use `kazagumo`- more easy shoukaku used wrapper update that it had new updates comes _so i say erela.js is no longer continued or getting any more updates so that why this need to be changed_
> 
> resuggest it make to updating library like poru

poru is the closest  to erela.js

**Comment by NotAditya69** [comment]
Changing to shoukaku would be a breaking change however
