### ISSUE TITLE
Spotify Link doesnt work

### ISSUE THREAD

**Issue by SZhang1337** [brblacky/lavamusic#247]
**Please describe the problem you are having in as much detail as possible:**

I was setting up the bot, i tried all type of method, everything worked, but Spotify didnt work at all.

<   STEP   >
1. Setup Bot 
2. npm install / lavalink setup
3. startup bot
4. !play or /play (spotify link)
5. Expect: it will auto find a same song in Youtube and start playing.
6. Result: Bot stop responding / Slash command shows (The application did not respond) / Console error.

![image](https://user-images.githubusercontent.com/54375883/184254044-b6be74c8-99aa-4350-919d-f2ed956b254b.png)

### Essentials:

- Commit Hash: 1
- Node.js version: v16.16.0
- Operating system: Ubuntu 20.04 LTS (VM X86)

#### Additional system info
- Is it virtualized? (Docker or ...) : Ubuntu 20.04 cloud-init vm
- What CPU is it running on (X86 or ARM or...): X86
- Additional details that might help us figure out the problem: typed at upper information

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by YuenTW** [comment]
Update:

Found out !p / !play (Spotify link) will work.

But when using slash command to play (Spotify link), the error code will show up in console and Bot wont start play the song.

**Comment by NotAditya69** [comment]
@LucasB25 you can close this, It's fixed
