### ISSUE TITLE
There was an error while searching: Loading information for a YouTube track failed.

### ISSUE THREAD

**Issue by LunarstarPony** [brblacky/lavamusic#248]
- Node.js version: 16.14.0
- Operating system: Rocky Linux 8
- Is it virtualized? (Docker or ...) : Virtual Machine
- What CPU is it running on (X86 or ARM or...): X86_64

Just setup LavaMusic on one of my Virtual Machine, everything seems to work but when I type !play "YoutubeLink" the bot just join and left immediately 
This is what it said in Discord: There was an error while searching: Loading information for a YouTube track failed.
and this is what it left in the console:
[14-08-2022 10:59:07]: [LOG] Player has been created in 869087768163266670
[14-08-2022 10:59:08]: [LOG] Player has been destroyed in 869087768163266670

**Comment by hatry4** [comment]
I think its your lavalink problem use freya codes jar and java 17 with docker

**Comment by LunarstarPony** [comment]
It does appear that it's a lava link issue and that fix it thanks alot!
