### ISSUE TITLE
Default Volume

### ISSUE THREAD

**Issue by LunarstarPony** [brblacky/lavamusic#250]
Is there a way to set the default volume when the bot joined since it's very loud at the default 80%?

**Comment by LucasB25** [comment]
you edit in the source code

**Comment by LunarstarPony** [comment]
Any idea where is it?

**Comment by LucasB25** [comment]
<https://github.com/brblacky/lavamusic/src/slashCommands/Music/play.js>

**Comment by LunarstarPony** [comment]
So it turns out changing the one in src/cmmands/Music/play.js change my default volume Thx!

**Comment by Foxie1171** [comment]
> So it turns out changing the one in src/cmmands/Music/play.js change my default volume Thx!

At what line you changed the required thing exactly? Can't seem to find anything related to volume
