### ISSUE TITLE
Erela.js "No Avaliable Nodes." RangeError

### ISSUE THREAD

**Issue by Sugger25e** [brblacky/lavamusic#26]
I've transfer the files to my bot as I forked this, and configure the event handler and error comes out:

```bash
/workspace/node_modules/erela.js/dist/structures/Player.js:82
            throw new RangeError("No available nodes.");
                  ^

RangeError: No available nodes.
    at new Player (/workspace/node_modules/erela.js/dist/structures/Player.js:82:19)
    at Manager.create (/workspace/node_modules/erela.js/dist/structures/Manager.js:205:16)
    at Object.run (/workspace/commands/music/play.js:23:49)
```

Any way to fix this?

**Comment by Rijus176** [comment]
Change lavalink

**Comment by Sugger25e** [comment]
I tried changing lavalink to default and it still doesn't work

"nodes": [ 
         {
      "host": "disbotlistlavalink.ml",
      "port": 443,
      "password": "LAVA",
      "identifier": "DisBotlist Lavalink",
      "retryDelay": 3000,
      "secure": true
         }
  ]

**Comment by brblacky** [comment]
Make your own lavalink server

**Comment by Sugger25e** [comment]
I already  made one and worked yesterday and after a few hours its broken
