### ISSUE TITLE
Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by RedolentHalo** [brblacky/lavamusic#261]
**Please describe the problem you are having in as much detail as possible:**

### Essentials:

- Commit Hash:
- Node.js version:16.17.0
- Operating system:windows

#### Additional system info
- Is it virtualized? (Docker or ...) :
- terminal
- What CPU is it running on (X86 or ARM or...):
- x86
- Additional details that might help us figure out the problem:
- SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (C:\Users\DELL\Downloads\lavamusic-main\node_modules\petitio\dist\index.js:30:574)
    at ke.json (C:\Users\DELL\Downloads\lavamusic-main\node_modules\petitio\dist\index.js:30:2499)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) uncaughtException
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y.json (C:\Users\DELL\Downloads\lavamusic-main\node_modules\petitio\dist\index.js:30:574)
    at ke.json (C:\Users\DELL\Downloads\lavamusic-main\node_modules\petitio\dist\index.js:30:2499)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) uncaughtException

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by Gremagol** [comment]
For some people, updating node to 17.9 fixed it, for some, it didnt. You could try that.

**Comment by LucasB25** [comment]
> **Please describe the problem you are having in as much detail as possible:**
> 
> ### Essentials:
> * Commit Hash:
> * Node.js version:16.17.0
> * Operating system:windows
> 
> #### Additional system info
> * Is it virtualized? (Docker or ...) :
> * terminal
> * What CPU is it running on (X86 or ARM or...):
> * x86
> * Additional details that might help us figure out the problem:
> * SyntaxError: Unexpected token  in JSON at position 0
>   at JSON.parse ()
>   at Y.json (C:\Users\DELL\Downloads\lavamusic-main\node_modules\petitio\dist\index.js:30:574)
>   at ke.json (C:\Users\DELL\Downloads\lavamusic-main\node_modules\petitio\dist\index.js:30:2499)
>   at processTicksAndRejections (node:internal/process/task_queues:96:5) uncaughtException
>   SyntaxError: Unexpected token  in JSON at position 0
>   at JSON.parse ()
>   at Y.json (C:\Users\DELL\Downloads\lavamusic-main\node_modules\petitio\dist\index.js:30:574)
>   at ke.json (C:\Users\DELL\Downloads\lavamusic-main\node_modules\petitio\dist\index.js:30:2499)
>   at processTicksAndRejections (node:internal/process/task_queues:96:5) uncaughtException
> 
> ### Relevant client options:
> * partials: none
> * gateway intents: none
> * other: none

https://nodejs.org/dist/v16.17.0/node-v16.17.0-x64.msi

**Comment by RedolentHalo** [comment]
Sir it got fixed by upgrading the node version thank you!
