### ISSUE TITLE
There was an error while searching: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by keboooooo** [brblacky/lavamusic#265]
I found a bug when I want to play music on discord, the bot joins into the voice channel but does not play the music. and also when I send a command I get the error "There was an error while searching: Unexpected token in JSON at position 0"

maybe someone can help with this

- Commit Hash: main
- Node.js version: v18.8.0
- Operating system: ubuntu 20.04.1

#### Additional system info
- Is it virtualized? (Docker or ...) : no
- What CPU is it running on (X86 or ARM or...): x86
- Additional details that might help us figure out the problem: it only happened with erela.js bot

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by Gremagol** [comment]
Change your Node version to 16.17 or 17.9 and please tell me which one worked afterwards. In the support server, 17.9 works best according to people having that issue.

**Comment by keboooooo** [comment]
using node 17.9 working fine
thanks @Gremagol 
![image](https://user-images.githubusercontent.com/71220458/187471772-af470476-7fbb-4f49-9084-004d093fa547.png)
