### ISSUE TITLE
bot doesnt send the play message and gives an error

### ISSUE THREAD

**Issue by scattyypie** [brblacky/lavamusic#272]
music still plays but the bot doesnt send the play message and gives an error https://cdn.discordapp.com/attachments/1000062086111567952/1016271171056058418/Capture.PNG
https://cdn.discordapp.com/attachments/942120037089689630/1016271662326485073/Capture.PNG

**Comment by scattyypie** [comment]
btw the bot has admin

**Comment by LucasB25** [comment]
#269
