### ISSUE TITLE
Error in src/SlashCommands/play.js

### ISSUE THREAD

**Issue by RafCodez** [brblacky/lavamusic#274]
Shows an error when u do /play
<img width="908" alt="Screenshot_2022-09-06_at_16 16 10" src="https://user-images.githubusercontent.com/89015458/188676188-6a23b30a-f08e-4fbf-8195-b73ed062f0e4.png">

**Comment by samrudd** [comment]
confirmed issue in nodejs 16/17/18

**Comment by LucasB25** [comment]
> Shows an error when u do /play <img alt="Screenshot_2022-09-06_at_16 16 10" width="908" src="https://user-images.githubusercontent.com/89015458/188676188-6a23b30a-f08e-4fbf-8195-b73ed062f0e4.png">
What kind of links were used for music?

**Comment by samrudd** [comment]
> Shows an error when u do /play <img alt="Screenshot_2022-09-06_at_16 16 10" width="908" src="https://user-images.githubusercontent.com/89015458/188676188-6a23b30a-f08e-4fbf-8195-b73ed062f0e4.png">
> What kind of links were used for music?

That’s what happens when searching but typing text into the /play command, no link used

**Comment by LucasB25** [comment]
What version of nodejs?

**Comment by samrudd** [comment]
i am currently running v17 but i have tried 16 and 18
