### ISSUE TITLE
Invalid Form Body when setting up slash commands

### ISSUE THREAD

**Issue by Legoman99573** [brblacky/lavamusic#276]
**Please describe the problem you are having in as much detail as possible:**
Just start the client and you eventually get this:
```applescript
DiscordAPIError[50035]: Invalid Form Body
0.options[0].name[STRING_TYPE_REGEX]: String value did not match validation regex.
    at SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:293:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
    at async REST.request (/home/container/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
    at async /home/container/src/handlers/slashCommand.js:51:7 {
  rawError: {
    code: 50035,
    errors: { '0': [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/<redacted>/commands',
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object]
    ]
  }
}
```

### Essentials:

- Commit Hash: https://github.com/brblacky/lavamusic/commit/97ff438bbe58ced04a8a0ca1e63cd4716a29e89a
- Node.js version: 18.8.0
- Operating system: CentOS Stream 8

#### Additional system info
- Is it virtualized? (Docker or ...) : Pterodactyl Panel
- What CPU is it running on (X86 or ARM or...): Xeon E5-2680v2 @ 2.8GHz / 3.6GHz max speed.
- Additional details that might help us figure out the problem: 

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by LucasB25** [comment]
https://nodejs.org/dist/v16.17.0/node-v16.17.0-x64.msi
uses this nodejs version to see

**Comment by Legoman99573** [comment]
I am still getting the same issue. Had no issue with the one in the releases tab. Must have been a change in one of the commits that broke it out of nowhere for me.

**Comment by NotAditya69** [comment]
**String value did not match validation regex.**

**Description**
Chat Input Command names and Option#names follows a certain regular expression if you violate it you run into this issue

RegExp - `^[-_\p{L}\p{N}\p{sc=Deva}\p{sc=Thai}]{1,32}$`

**Solution**
Your problem is from the Chat Input Options so you would have to check from where it is and then once you locate it check for the name field if it contains any special characters or uppercase letter then just remove them, A tip to locate it is checking the options array index 0

**Comment by LucasB25** [comment]
I can close?

**Comment by Legoman99573** [comment]
I will still need to look through to see why it's being caused as it's not telling me where it is as it's just saying it's in slashcommands.js and doesnt help narrow down the culprit.

**Comment by Legoman99573** [comment]
Does not need to be re-opened, but when you use v10 of the API, the error seems to go away all of a sudden. I would have probably needed to check I was using the right API version as v8 is pretty outdated. Maybe this will help others out in the future if they get something like this.
