### ISSUE TITLE
Play Command 

### ISSUE THREAD

**Issue by TechiePotato** [brblacky/lavamusic#284]
Play Command doesn't working in slash it's always search the word input instead of what I search my humble request to fix the issue as soon as possible.

**Comment by NotAditya69** [comment]
Are using the latest source the recently pushed one? Since it contains the fix for it

**Comment by NotAditya69** [comment]
@LucasB25 you can close this he probably fixed it i think

**Comment by LucasB25** [comment]
> @LucasB25 you can close this he probably fixed it i think

he would have to confirm
