### ISSUE TITLE
Setup channel bug

### ISSUE THREAD

**Issue by RedolentHalo** [brblacky/lavamusic#286]
**Please describe the problem you are having in as much detail as possible:**

### Essentials:

- Commit Hash:
- Node.js version: 17
- Operating system: Linuz

#### Additional system info
- Is it virtualized? (Docker or ...) : Docker
- What CPU is it running on (X86 or ARM or...):ARM
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: all
- gateway intents: all
- other: all
In the setup channel when the playlist or the song is added to queue it doesn't delete the name / link please fix it!

![image](https://user-images.githubusercontent.com/86344714/190857035-3bbbaa77-1463-4137-9a6d-9c2e3d885b0e.png)

**Comment by NotAditya69** [comment]
Are you using the latest release?

**Comment by RedolentHalo** [comment]
ig am not but where can i find the fix? i would like to know
