### ISSUE TITLE
24/7not working

### ISSUE THREAD

**Issue by Midul42** [brblacky/lavamusic#290]

**Comment by LucasB25** [comment]
Explain yourself more about this problem!

**Comment by Midul42** [comment]
The bot left vc after 3-6 hours. And say "I have been left from vc"
He Don't stay in vc for 24/7 with 247 command.🙂

**Comment by LucasB25** [comment]
the concern comes from the lavalink server that you use not the bot

**Comment by Midul42** [comment]
> the concern comes from the lavalink server that you use not the bot

When lavalink off?

**Comment by Midul42** [comment]
> the concern comes from the lavalink server that you use not the bot

When lavalink off?

**Comment by LucasB25** [comment]
the problem comes from the lavalink server you use (the one that manages the music)

**Comment by Midul42** [comment]
Can you give a link of >> How to host a perfect lavalink?

**Comment by LucasB25** [comment]
It doesn’t exist, just having a good vps
