### ISSUE TITLE
Not registered

### ISSUE THREAD

**Issue by XenonDevZ** [brblacky/lavamusic#291]
When i click the buttons it sends You are not registered
![Screenshot_2022-09-21-00-42-00-864_com bluecord](https://user-images.githubusercontent.com/91532450/191316656-4e042eb5-d1ea-4cd0-8ccd-a087830623b2.jpg)

**Comment by NotAditya69** [comment]
Are you using the latest release?

**Comment by NotAditya69** [comment]
@XenonDevZ this doesn't seems to be a part of the official repo you have probably messed up somewhere when modifying the code
