### ISSUE TITLE
1. Dont use my Name, 2. dont use my avatar, 3. give me credits for my code

### ISSUE THREAD

**Issue by Tomato6966** [brblacky/lavamusic#3]
*OR I WILL TAKE THIS GITHUB REPO WITH DMCA AS WELL AS YOUR DISCORD ;)*

**Comment by brblacky** [comment]
Oo hello fast lavamusic logo I have copyright and code who are you This is not your code

**Comment by brblacky** [comment]
This logo From victorart.com

**Comment by brblacky** [comment]
And you don't know coding alone, everyone knows more or less

**Comment by Bedrock16** [comment]
> This logo From Signal Chain
> Lava Music – Signal Chain

Hey but the logo seems copied of his bot

**Comment by Tomato6966** [comment]
Dude Lava Music 
![image](https://user-images.githubusercontent.com/68145571/131617289-9bdb8da6-0d5c-4ec3-8caa-dc2724a3d941.png)
Is **MY BOT**
Invite link:
https://lava.milrato.dev

Sample Bot list redirect:
https://botlist.milrato.eu/bot/742672021422342165


Here is the original Repository:
https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js


Last warning!

**Comment by brblacky** [comment]
Bro do you have your logo copyright ?

**Comment by brblacky** [comment]
This logo for commercial use

**Comment by brblacky** [comment]
> > This logo From Signal Chain
> > Lava Music – Signal Chain
> 
> Hey but the logo seems copied of his bot

This logo for commercial use so any one can use

**Comment by brblacky** [comment]
> Now you already changed the code thats alright
> but the logo...

This is not your logo  this is from 
https://signalchain.com.au/collections/lava-music

**Comment by Tomato6966** [comment]
It is very similar to what is my logo but my logo is selfdesigned 
From plain gimp i just noticed its not the same as yours i was in a rush back then

**Comment by wh0isrh** [comment]
don't worry tomato, this skid is a kid, and dont know coding, he take a lot of script and remakes^^

**Comment by Bedrock16** [comment]
But still you copied name

**Comment by wh0isrh** [comment]
skid @Bedrock16 @brblacky

**Comment by Bedrock16** [comment]
> skid @Bedrock16 @brblacky

What do you mean
