### ISSUE TITLE
NOT WORKING PROPLEM 

### ISSUE THREAD

**Issue by abdalrahman153** [brblacky/lavamusic#300]
**Please describe the problem you are having in as much detail as possible:**

### Essentials:

- Commit Hash:
- Node.js version:
- Operating system:

#### Additional system info
- Is it virtualized? (Docker or ...) :
- What CPU is it running on (X86 or ARM or...):
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by abdalrahman153** [comment]
.

**Comment by Gremagol** [comment]
Since you didnt specify anything we asked for in the form we can't really help you.

**Comment by LucasB25** [comment]
> **Please describe the problem you are having in as much detail as possible:**
> 
> ### Essentials:
> * Commit Hash:
> * Node.js version:
> * Operating system:
> 
> #### Additional system info
> * Is it virtualized? (Docker or ...) :
> * What CPU is it running on (X86 or ARM or...):
> * Additional details that might help us figure out the problem:
> 
> ### Relevant client options:
> * partials: none
> * gateway intents: none
> * other: none

Explain your concern better!
