### ISSUE TITLE
Auto vc after restart 

### ISSUE THREAD

**Issue by Yash143220** [brblacky/lavamusic#302]
### Description of your suggestion

If bot hoes offline and when it comes online it automatically connected the vc in which 247 was active. And if 247 is enabled then no one can disconnect the bot if does then bot automatically connect again untill 247 is disabled

**Comment by Legoman99573** [comment]
Only issue is that the bot doesn't seem to remember 24/7 status on bot restart.

**Comment by NotAditya69** [comment]
Alright I'll look into it
