### ISSUE TITLE
stop music

### ISSUE THREAD

**Issue by Alone-ankush** [brblacky/lavamusic#307]
### Bug description

bhai,bot ko server mute deke usi time server unmute krne ke baad.bot ko jb tak disconnect krke waaps connect na kru,tabtk music nhi bjata..kitna v skip vgair krlo..nhi bajta

### Step to reproduce

ask @NotAditya69 yo know more

### Operating system

bhai window 8 pro hai..aur mai pc ka use bilkul nhi kr rha

### Nodejs version

jo esme tumlogo ne dala hai vhi hai

### Errors / Logs

not throwing any error.

**Comment by LucasB25** [comment]
explain in the universal language thank you!
