### ISSUE TITLE
music bug found

### ISSUE THREAD

**Issue by Alone-ankush** [brblacky/lavamusic#308]
### Bug description

when i server mute the bot while playing songs,nd unmute them...after server unmute bot doesn't play any songs.for play next song.i have to disconnect the bot from vc..and have to join again to play any music again.

### Step to reproduce

litterly,don't know,what is this for.

### Operating system

windows 8

### Nodejs version

17.9.1

### Errors / Logs

no error throw.

**Comment by RedolentHalo** [comment]
Hmm it's cause it pauses the queue unpause it using button

**Comment by Alone-ankush** [comment]
it's a bug,fix it :)
