### ISSUE TITLE
disconnection

### ISSUE THREAD

**Issue by Yash143220** [brblacky/lavamusic#314]
### Bug description

mongo and lavalink get disconnect after sometime and again reconnect . and happen again after some hour .

it affect 247 vc also songs stop 

### Step to reproduce

run the bot 

### Operating system

linux

### Nodejs version

v17

**Comment by penchuri** [comment]
Yes same issue hope the fix this asap

**Comment by NotAditya69** [comment]
this isn't a issue from the repo please monitor your network, when connections are established they would either be disconnected because of network

**Comment by Yash143220** [comment]
But many user face same pblm i host it on very good vps

**Comment by NotAditya69** [comment]
how many users?

**Comment by NotAditya69** [comment]
you are the first one to actually talk about this problem

**Comment by Yash143220** [comment]
Mt friends facing same pblm bot running perfectly fine but after some hour mongo and node disconnect and reconnect

**Comment by NotAditya69** [comment]
this requires personal support the repo uses traditional connections methods, Please join the support server for further assistance

**Comment by penchuri** [comment]
> My friends facing same pblm bot running perfectly fine but after some hour mongo and node disconnect and reconnect

Also happen to me

**Comment by NotAditya69** [comment]
as i said join the support server

**Comment by RedolentHalo** [comment]
It's not the problem from the source it leaves the voice channel because of the lavalink the player is connected to gets disconnected from your bot's network

**Comment by penchuri** [comment]
tutup

**Comment by NotAditya69** [comment]
@LucasB25 this is resolved both of them were invited to support server for personal assistance this isn't a issue with the repo therefore you can close this
