### ISSUE TITLE
Player Volume

### ISSUE THREAD

**Issue by PandaIN95** [brblacky/lavamusic#316]
### Description of your suggestion

Can we add a feature where we can set default volume level per guild

**Comment by NotAditya69** [comment]
Isn't the Player#setVolume for per guild anyways since a player is created through three properties guildId, voice channel, text channel therefore anychanges on a player will change for the guild you are doing it for

**Comment by Legoman99573** [comment]
Its not saved and gets lost on bot restart just like 24/7 use to be like before it was fixed up (not perfectly, but the bugs will get squashed eventually) through several commits. Probably add it into the guilds as an option to store in MariaDB.
