### ISSUE TITLE
24/7 

### ISSUE THREAD

**Issue by penchuri** [brblacky/lavamusic#318]
### Bug description

When using the stop command while the 24/7 command is enabled the bot doesn’t leave but sends a message Player has been disconnected from the voice channel 

![04B2D510-FC67-4498-8A72-F89E5825ACD6](https://user-images.githubusercontent.com/112509490/194754530-d2cbe3e9-fefc-4cfc-8933-979866f41917.jpeg)
![1CBFB1DA-FC60-41C5-9C5C-1123244BDE92](https://user-images.githubusercontent.com/112509490/194754535-ec3d5843-9ece-4338-b3ef-72818467b65f.jpeg)

### Step to reproduce

Maybe just fix some word

### Operating system

Linux

### Nodejs version

17.x.x

**Comment by NotAditya69** [comment]
This is not a bug it's intentional it's obvious if 24/7 is enabled the bot will try to rejoin since it's supposed to stay in the vc turn 24/7 off if you want to make the bot leave, Also when opening a issue first read the code.

**Comment by NotAditya69** [comment]
To add a embed open a pr
