### ISSUE TITLE
Fix Socket has been closed because Session is no longer valid.

### ISSUE THREAD

**Issue by socktow** [brblacky/lavamusic#32]
Go to : events/Lavalink/socketClosed.js
Old : 
`module.exports = async (client, player, payload) => {

	if (payload.byRemote == true) {
        player.destroy();
    }

    client.logger.log(`Socket has been closed because ${payload.reason} in [${player.guild}]`, "error");
}
`

Edit : 

`module.exports = async (client, player, payload) => {

    console.error();

}
`

**Comment by brblacky** [comment]
Fixed

**Comment by sarcasternub** [comment]
How did you fix this?

**Comment by LucasB25** [comment]
@sarcasternub if it’s flagged as fixed, then it’s set

**Comment by sarcasternub** [comment]
@LucasB25 that's not what I meant. I am not using this repo/bot. It's just that I got the same issue in my bot and I want to fix it so asking for the commit in which he/she fixed this issue or atleast slide me a solution.

**Comment by LucasB25** [comment]
Well yes this problem has been solved, but I don’t know the origin of the patch
