### ISSUE TITLE
Main engine 

### ISSUE THREAD

**Issue by penchuri** [brblacky/lavamusic#320]
### Description of your suggestion

I have a suggestion maybe remove youtube as the main streaming feature on this open source lots of music bots have started using Spotify as their main music stream that's all for my suggestion thank you for making this masterpiece

**Comment by NotAditya69** [comment]
they use metadata actually they can't stream from spotify if you can add it in lavamusic feel free to open a pull request

**Comment by nfsmaniac** [comment]
To remove YouTube when it is already there is a bad idea, anyway.
While it is possible to create alternative client to the official ones provided by Spotify, Tidal, etc., they DO REQUIRE to be paired (logged in) with an account with active Premium subscription.
The right question here is not who will implement it, but who will pay it. Especially, when there's a risk that the account with paid subscription might be banned at any time, as using it for this purpose most likely violates some term of service (Spotify).

**Comment by penchuri** [comment]
> To remove YouTube when it is already there is a bad idea, anyway. While it is possible to create alternative client to the official ones provided by Spotify, Tidal, etc., they DO REQUIRE to be paired (logged in) with an account with active Premium subscription. The right question here is not who will implement it, but who will pay it. Especially, when there's a risk that the account with paid subscription might be banned at any time, as using it for this purpose most likely violates some term of service (Spotify).

Oh got it i have question how i can make when put youtube link it doest play just send a message like you cant use youtube link

**Comment by Nico-ITA** [comment]
> > To remove YouTube when it is already there is a bad idea, anyway. While it is possible to create alternative client to the official ones provided by Spotify, Tidal, etc., they DO REQUIRE to be paired (logged in) with an account with active Premium subscription. The right question here is not who will implement it, but who will pay it. Especially, when there's a risk that the account with paid subscription might be banned at any time, as using it for this purpose most likely violates some term of service (Spotify).
> 
> Oh got it i have question how i can make when put youtube link it doest play just send a message like you cant use youtube link

simply: 
 if (  search.includes("youtube.com") )  ---> send a message like " YouTube is not supported "  where search contain what the user sent by the command or interaction

**Comment by penchuri** [comment]
> if ( search.includes("youtube.com") )

I’m really sorry can you explain more easy to understand thank uou

**Comment by Nico-ITA** [comment]
> 
 you can use the includes() function that check if in a string there is a specific word ( in this case "yotube.com" . So if there is youtube.com inside send a message that yt is not longer supported . Otherwise continue with all the code

**Comment by penchuri** [comment]
> you can use the includes() function that check if in a string there is a specific word ( in this case "yotube.com" . So if there is youtube.com inside send a message that yt is not longer supported . Otherwise continue with all the code

Oh bit understand can you give me examples how the code will look like in the play.js?

**Comment by Nico-ITA** [comment]
> > you can use the includes() function that check if in a string there is a specific word ( in this case "yotube.com" . So if there is youtube.com inside send a message that yt is not longer supported . Otherwise continue with all the code
> 
> Oh bit understand can you give me examples how the code will look like in the play.js?

Under line #66 of play.js (Slash commands) put this : 

 if(search.includes("youtube.com") ) { 

  return interaction.editReply({
        embeds: [
          new EmbedBuilder()
            .setColor(client.embedColor)
            .setDescription(
              `YouTube is no longer supported ! Use Spotify foe example .`
            ),
        ],
      });
}

**Comment by penchuri** [comment]
> if(search.includes("youtube.com") ) {
> 
> return interaction.editReply({ embeds: [ new EmbedBuilder() .setColor(client.embedColor) .setDescription( `YouTube is no longer supported ! Use Spotify foe example .` ), ], }); }

It give me this error 
/home/container/src/slashCommands/Music/play.js:74
YouTube is no longer supported ! Use Spotify foe example .),
^^^^^^^
SyntaxError: missing ) after argument list
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/container/src/handlers/slashCommand.js:14:28

**Comment by Nico-ITA** [comment]
https://pastebin.com/Zv1HBd1X  copy the code from pastebin

**Comment by penchuri** [comment]
> https://pastebin.com/Zv1HBd1X copy the code from pastebin

Thank you so much it work ❤️

**Comment by penchuri** [comment]
> https://pastebin.com/Zv1HBd1X copy the code from pastebin

It work on first link and after i put different yt link it doest work

**Comment by Nico-ITA** [comment]
> > https://pastebin.com/Zv1HBd1X copy the code from pastebin
> 
> It work on first link and after i put different yt link it doest work

what do u mean ?

**Comment by penchuri** [comment]
> > > https://pastebin.com/Zv1HBd1X copy the code from pastebin
> > 
> > 
> > It work on first link and after i put different yt link it doest work
> 
> what do u mean ?

Nvm it fixed anyway thank you so much

**Comment by Nico-ITA** [comment]
> > > > https://pastebin.com/Zv1HBd1X copy the code from pastebin
> > > 
> > > 
> > > It work on first link and after i put different yt link it doest work
> > 
> > 
> > what do u mean ?
> 
> Nvm it fixed anyway thank you so much

np
