### ISSUE TITLE
Song in playlist skips after being resumed after inactivity on 24/7 mode

### ISSUE THREAD

**Issue by UnconsciousPebble** [brblacky/lavamusic#321]
### Bug description

Songs queued from a YouTube playlist (invoked from a user playlist) randomly skip from time to time when they are resumed upon joining the music channel and the bot resuming playback on 24/7 mode with queue looping mode after just a few seconds of playback.

### Step to reproduce

Leave channel with 24/7 mode on playing from a youtube playlist, apparently it happens more often when the song has advanced in time and when you joined hours later, but I'm not sure of the pattern.

### Operating system

 Ubuntu 22.04

### Nodejs version

17.9

**Comment by LucasB25** [comment]
This concern comes from the LavaLink server using
