### ISSUE TITLE
Spotify Bot 

### ISSUE THREAD

**Issue by backup5** [brblacky/lavamusic#327]
### Description of your suggestion

Hey ,
this feature shall useful
as there is no video on google how to make a spotify only music bot pls change lavamusic to spotify 

and i also need spotify as some people play songs with 18+ images and also play bad videos of there channel

hope u will agree

**Comment by penchuri** [comment]
> ### Description of your suggestion
> Hey , this feature shall useful as there is no video on google how to make a spotify only music bot pls change lavamusic to spotify
> 
> and i also need spotify as some people play songs with 18+ images and also play bad videos of there channel
> 
> hope u will agree

Yup really good cause youtube is not relevant anymore since youtube doesn’t want their api got use in music bot

**Comment by Legoman99573** [comment]
Some issues as setting a default provider should be left up to the bot owner, but there is other flaws
> as there is no video on google how to make a spotify only music bot pls change lavamusic to spotify

Not everyone will use the Spotify API and some will stick with YouTube or other services provided by LavaLink.


> and i also need spotify as some people play songs with 18+ images and also play bad videos of there channel

Not all servers are the same and should be left up to the guild if they want to moderate it or not. Plus you can connect your spotify options in ``.env`` and using a spotify URL should work. Plus Spotify has its limits on how many shards you can use them on before its maxed out and has to be manually approved by spotify to increase the numbers, which is not easy to get approved either.

**Comment by Yash143220** [comment]
yes make it spotify only
