### ISSUE TITLE
Search Result & Play Command

### ISSUE THREAD

**Issue by erwinowak** [brblacky/lavamusic#335]
### Description of your suggestion

Maybe the author of this great bot will think to change the search method, because what I would like to search for is always the same result. And maybe instead of these buttons change the reactions with pagination?

And the same is with the **/play** command, when I enter the title I am looking for in input, it shows me only 5 results and none is close to the search.

![Screenshot_1](https://user-images.githubusercontent.com/809818/196019218-cfe7fe42-876e-446b-beaf-45f1f7d89137.png)

![Screenshot_2](https://user-images.githubusercontent.com/809818/196019408-986f25dc-5e99-4d60-933d-02501180ea21.png)

I am asking the author to consider such a change :blush:

**Comment by blaumath** [comment]
First go to src/structures/Lavamusic.js in the line 298  defaultSearchPlatform: "youtube music''  change to youtube and restart the bot

**Comment by Legoman99573** [comment]
Maybe I can make a config option for it for those who don't want to dig that deep.

**Comment by Legoman99573** [comment]
> First go to src/structures/Lavamusic.js in the line 298 defaultSearchPlatform: "youtube music'' change to youtube and restart the bot

Pushed a pull request. If accepted, then there will be no use in doing that and is good for keeping up with later versions without having to go back and add it back in.
