### ISSUE TITLE
bug in seek command

### ISSUE THREAD

**Issue by Alone-ankush** [brblacky/lavamusic#338]
### Bug description

when i just type only **!seek** word,it's throwing error.

![IMG_20221016_160840](https://user-images.githubusercontent.com/79055580/196030794-06107d6e-9273-4d04-a6d9-6db4ca39866e.jpg)

**Comment by Legoman99573** [comment]
Usage is ``!seek <10s || 10m || 10h || HH:mm:ss || mm:ss || mm ss>`` or ``/seek <10s || 10m || 10h || HH:mm:ss || mm:ss || mm ss>``

Try one of those with the latest commit and tell me if it still occurs.

**Comment by nfsmaniac** [comment]
I use mostly Slash commands, so sorry for introducing this bug, as I was mostly copy-pasting Slash logic.
Previous fix [lavamusic/pull/332](https://github.com/brblacky/lavamusic/pull/332) was incompatible with my later improvements of the Seek commans.
