### ISSUE TITLE
LavaLink Monitor Container Won't Start

### ISSUE THREAD

**Issue by xCrazyIan** [brblacky/lavamusic#341]
### Bug description

Hello,

I am having issues with the lava link monitor container. When I start it up, I get the following error:
![image](https://user-images.githubusercontent.com/104403098/196061207-ca3f79bd-dbde-489b-a182-1638c3941a8c.png)

I believe this is an issue with the channel ID. Is there a different format I should be using instead of what I have in my docker-compose file:
![image](https://user-images.githubusercontent.com/104403098/196061266-fe1551ee-5966-4443-ba2b-9d053c721297.png)

Thanks!

### Step to reproduce

When I run the lava-music container, it keeps running into an error and never starts up. I see the bot goes online, but it seems to be having an issue with the channel id.

### Operating system

Raspberry PI OS Lite 64-bit

### Nodejs version

16.16.0

**Comment by NotAditya69** [comment]
read the error it's not related to your lavalink it's the channel that couln't be found, check your id on the fetch method

**Comment by xCrazyIan** [comment]
Very stupid solution on my end. If anyone runs into the same problem, the docker-compose file is incorrect. The environment variable for the channel id is not correct it should be "LOGS".

![image](https://user-images.githubusercontent.com/104403098/196991640-7b496933-091f-4078-86a5-30646a731368.png)
