### ISSUE TITLE
Fix search limit for playing songs

### ISSUE THREAD

**Issue by gif12** [brblacky/lavamusic#343]
### Description of your suggestion

Hi 
In version `1.0.6`, these restrictions did not exist and we could search for the title of any song on YouTube to find and play it.
 But in this new version, when we search the title of some videos for playback, an unrelated result is displayed

For example, if we search for `دکتر استاپ`, the following song will be played in version `1.0.6`:
 [https://www.youtube.com/watch?v=T416liv1Q-o](https://www.youtube.com/watch?v=T416liv1Q-o) 
 But if we search for the same phrase in the new version, the following song will be played, which has nothing to do with the search we made:
 [https://www.youtube.com/watch?v=eDqWWbO6e1k](https://www.youtube.com/watch?v=eDqWWbO6e1k) 

 I have run both versions with a lavalink so it's not a lavalink problem

I think a search limit has been added in the new version

**Comment by nfsmaniac** [comment]
Can you provide example search query?
I can't tell as I am pretty new to LavaMusic bot, but maybe it is due to YouTube Music being as the default source.
Try the latest commit, and set `SearchPlatform: process.env.searchPlatform || "youtube" in `src/config.js` and check, if it any helps.

**Comment by gif12** [comment]
For example, if we search for `دکتر استاپ`, the following song will be played in version `1.0.6`:
 [https://www.youtube.com/watch?v=T416liv1Q-o](https://www.youtube.com/watch?v=T416liv1Q-o) 
 But if we search for the same phrase in the new version, the following song will be played, which has nothing to do with the search we made:
 [https://www.youtube.com/watch?v=eDqWWbO6e1k](https://www.youtube.com/watch?v=eDqWWbO6e1k) 

 I have run both versions with a lavalink so it's not a lavalink problem

I think a search limit has been added in the new version

**Comment by nfsmaniac** [comment]
Thank you for the example.
It is indeed caused by the `YouTube Music` search results.
So no "filter" is there, it's just switch to another provider, where "studio" music results are preferred over user uploads.
Here a comparison of search results from both `YouTube` and `YouTube Music` on the bot's latest version.

![image](https://user-images.githubusercontent.com/3188999/196284832-c4a3de0f-cb72-49cd-b030-7f7e07635ab3.png)

**Comment by Legoman99573** [comment]
Thank god I introduced #340 so people can switch providers a lot easier.

**Comment by nfsmaniac** [comment]
I am thinking about making some multi-search feature, which might be quite cool. Because, currently, still, the choice is up on the bot's maintainer and not up to the end user.

**Comment by Legoman99573** [comment]
> I am thinking about making some multi-search feature, which might be quite cool. Because, currently, still, the choice is up on the bot's maintainer and not up to the end user.

Would be nice to allow server owners to select a platform, but the only issue is that it would need to be stored in the database to prevent loss on server restart.

**Comment by gif12** [comment]
> Thank you for the example. It is indeed caused by the `YouTube Music` search results. So no search "limit" is there, it had just been switched to another provider, where "studio" music results are preferred over user uploads. Here a comparison of search results from both `YouTube` and `YouTube Music` on the bot's latest version.
> 
> ![image](https://user-images.githubusercontent.com/3188999/196284832-c4a3de0f-cb72-49cd-b030-7f7e07635ab3.png)

oh Thankful 😄
