### ISSUE TITLE
Bug SlashCMD

### ISSUE THREAD

**Issue by rikvip08** [brblacky/lavamusic#36]
even though I invited bot with scopes **_application.commands_** but **slash commands** still can't deploy to Server. I've tried kicking and re-invite many times but it still doesn't work

![2](https://user-images.githubusercontent.com/53942684/140848311-7732eb90-5668-47f5-92c4-c4701bfa244c.png)
![3](https://user-images.githubusercontent.com/53942684/140848323-7acc21d9-f3f2-47bc-aae4-ef0a4ca85ef2.png)
![1](https://user-images.githubusercontent.com/53942684/140848350-4570e5ca-a618-4508-8910-1ab643167053.png)

**Comment by EliRickard** [comment]
Did you find a solution for this?

**Comment by brblacky** [comment]
It is fixed update coming soon
