### ISSUE TITLE
[ Queue & Nowplaying ] Commands

### ISSUE THREAD

**Issue by REMOOO** [brblacky/lavamusic#37]
We need to make the **Queue** command like this ..
![1](https://user-images.githubusercontent.com/13511097/141877401-d1be1627-9f81-40e8-b194-cdb840d15a0d.PNG)

and **Nowplaying** command like this ..
![2](https://user-images.githubusercontent.com/13511097/141877413-343f47c5-bb67-4c98-a836-e4ba028d071e.PNG)

**Comment by brblacky** [comment]
Added
