### ISSUE TITLE
Interaction Error

### ISSUE THREAD

**Issue by REMOOO** [brblacky/lavamusic#372]
### Bug description

Interaction has already been acknowledged.
This error in filters.js in this line `if (!b.replied) await b.deferUpdate({ ephemeral: true });`

### Step to reproduce

how to solve?

### Operating system

Windows

### Nodejs version

v18

### Errors / Logs

An Error Occured:
DiscordAPIError[40060]: Interaction has already been acknowledged.

**Comment by NotAditya69** [comment]
Can you tell the location? Aka the file name where this issue is located

**Comment by nfsmaniac** [comment]
> Can you tell the location? Aka the file name where this issue is located

https://github.com/brblacky/lavamusic/blob/dec8eae4dae1ba210545758348c8f012bb1bcc3c/src/commands/Music/filters.js#L57

**Comment by REMOOO** [comment]
filters.js
@NotAditya69

**Comment by nfsmaniac** [comment]
@REMOOO Could you help us by further description of the issue? How and when it will occur? Are more users interacting with the bot at the same time or just you? Please, provide detailed steps to reproduce it.

**Comment by REMOOO** [comment]
![Screenshot 2022-11-06 222621](https://user-images.githubusercontent.com/13511097/200193389-d74dcb50-44ae-43f4-af77-e7672ecc6def.png)

Error line : `await i.deferReply({ ephemeral: false, });`

**Comment by nfsmaniac** [comment]
You need to specify, what are you doing from a user perspective.
Do Slash command `/filters` work normally?
I am struggling to make this error ever happen, when I simply use the `!filters` command and apply any of the effects.
Try to update to the latest version. In case you've been doing any modification, you can try to silent the issue by yourself by encapsulating the incrimined line into try-catch block, a.k.a.
`try { await i.deferReply({ ephemeral: false, }); } catch(err) {};`

**Comment by LucasB25** [comment]
@REMOOO please answer the questions to correct the problem!
