### ISSUE TITLE
Remove pause messages when player resumes

### ISSUE THREAD

**Issue by scattyypie** [brblacky/lavamusic#374]
### Description of your suggestion

Remove pause messages when player resumes and remove the resume message too after 30 seconds so it looks clean
![image](https://user-images.githubusercontent.com/102586120/199043258-14f05c8a-d7f6-4ec8-869d-1b2e7971b11e.png)
these messages dont look good lol and they wont go away until you delete them yourself

**Comment by REMOOO** [comment]
you can delete it easy bro
