### ISSUE TITLE
Bot Offline

### ISSUE THREAD

**Issue by REMOOO** [brblacky/lavamusic#376]
### Bug description

lavamusic leaves the room and becomes offline, and when I see the console, there are no errors how to know what problem ?

### Step to reproduce

lavamusic leaves the room and becomes offline, and when I see the console, there are no errors how to know what problem ?

### Operating system

Windows

### Nodejs version

>=18

### Errors / Logs

lavamusic leaves the room and becomes offline, and when I see the console, there are no errors how to know what problem ?

**Comment by NotAditya69** [comment]
It becomes offline? It probably has something to do it the websocket if it doesn't resume it's connection within X milliseconds it gets terminated refer to https://discord.dev or https://discord.gg/discord-developers and if you have edited the discord.js library or its the cause ask help ther https://discord.gg/discordjs
