### ISSUE TITLE
Playlist name can't be greater than 10 characters.

### ISSUE THREAD

**Issue by alez007** [brblacky/lavamusic#380]
### Description of your suggestion
When I want to create a playlist, e.g. using `/create name: IBIZA SUMMER MIX 2021` I get the following error:
`Playlist name can't be greater than 10 characters. `

Any reason for this limitation? I personally don't see why we can't save playlists using more characters.

Cheers

**Comment by nfsmaniac** [comment]
I guess it was decided to enforce the user to be short and ensure clean and one-line results from `/list` command.
However, I also see 10 characters as a way too restrictive limit. #381

**Comment by alez007** [comment]
cheers, yeah 100 would do, with 10 chars my head explodes before I come up with something meaningful :D

**Comment by alez007** [comment]
I can confirm this is now working, thanks!
