### ISSUE TITLE
Possible to know what server the bot is currently in?

### ISSUE THREAD

**Issue by LunarstarPony** [brblacky/lavamusic#396]
### Description of your suggestion

I can see that in STATISTICS it show how many server the bot is currently in but is it possible to know the name of the server? Want to make sure the bot is only the server's I know about.

**Comment by LunarstarPony** [comment]
I'm pretty sure I have mine set but the bot doesn't seems to be responding?

**Comment by LunarstarPony** [comment]
Is there a way to check if the ID is being set corretly

**Comment by LunarstarPony** [comment]
It does indeed look like dis 163303458445852673

**Comment by LunarstarPony** [comment]
Unless this one isn't correct?

**Comment by LunarstarPony** [comment]
orrr

**Comment by LucasB25** [comment]
user serverinfo

**Comment by LunarstarPony** [comment]
Is that a command? 

> use serverinfo

**Comment by LunarstarPony** [comment]
As I still doesn't get any respond by typing this command

**Comment by LucasB25** [comment]
error ?

**Comment by LunarstarPony** [comment]
I type it in the server that it's in the bot just doesn't respond at all with the command

**Comment by LunarstarPony** [comment]
It pretty much just completely ignore it(

**Comment by LunarstarPony** [comment]
I might recheck again see if the owner ID is set correctly

**Comment by LucasB25** [comment]
my bad: use [serverlist.js](https://github.com/brblacky/lavamusic/blob/main/src/commands/Owner/serverlist.js)

**Comment by LunarstarPony** [comment]
> my bad: use [serverlist.js](https://github.com/brblacky/lavamusic/blob/main/src/commands/Owner/serverlist.js)

How would I use this do I need to execute it on the Linux Server or Discord Server?

**Comment by LunarstarPony** [comment]
So I just check the directory /lavamusic/src/commands/Owner and the only file in there is eval.js

**Comment by LunarstarPony** [comment]
That's probably why It never respond with that command for me?

**Comment by LunarstarPony** [comment]
Yeah I'll try to update it rn(

**Comment by LunarstarPony** [comment]
So after updating the command seems to be working now but now when I tried to execute status it shows the following in terminal. Any idea what's wrong?
```
[AntiCrash] | [UnhandledRejection_Logs] | [start] : ===============                                                             │················································································································
TypeError: Cannot read properties of null (reading 'ids')                                                                       │················································································································
    at Object.execute (/home/lunarstarpony/lavamusic/src/commands/Information/status.js:37:60)                                  │················································································································
    at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                       │················································································································
[AntiCrash] | [UnhandledRejection_Logs] | [end] : ===============
```

**Comment by LunarstarPony** [comment]
Or should I open a new ticket for this one(

**Comment by StarnightFox** [comment]
@LunarstarPony Line 37:60 should be ```.setFooter({ text: `You are in shard [${client.shard.ids[0]}]` })```
If your bot isn't big enough for sharding yet, change it to 
change it to ```.setFooter({ text: `You are in shard [0]` })``` or something similar

**Comment by LunarstarPony** [comment]
That fix it thank you! < 3

**Comment by Xenofic** [comment]
this workaround is not preferred instead use ` ... || 0`

**Comment by StarnightFox** [comment]
I mean, it's just a string of text that only changes when the bot is in what, like 1k servers or more? At which point, given the fact they only want the bot in servers they know about, it's perfectly fine to do. A better thing would be to turn off sharding entirely and to private the bot in the discord dev application

**Comment by LunarstarPony** [comment]
So I recently reinstall Lavamusic and wonder if this command still works? it doesn't seems to exist anymore
