### ISSUE TITLE
ChannelType is not defined       

### ISSUE THREAD

**Issue by vanna-code** [brblacky/lavamusic#399]
### Bug description

after join server then in terminal send this 

ReferenceError: ChannelType is not defined

### Step to reproduce

ReferenceError

### Operating system

window

### Nodejs version

18.x

### Errors / Logs

    at C:\Users\Vanna\Desktop\botmusic\src\events\Client\guildCreate.js:13:22
    at Collection.forEach (<anonymous>)
    at Object.run (C:\Users\Vanna\Desktop\botmusic\src\events\Client\guildCreate.js:12:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by LucasB25** [comment]
What branch of lavaMusic?

**Comment by vanna-code** [comment]
> 

yes lavamusic

**Comment by LucasB25** [comment]
what branche ?

**Comment by LucasB25** [comment]
![image](https://user-images.githubusercontent.com/50886682/207398090-21b9985e-02b5-49c3-968a-02e2771a0b70.png)
What branch is your problem?
