### ISSUE TITLE
New Lavamusic [Spotify]

### ISSUE THREAD

**Issue by REMOOO** [brblacky/lavamusic#405]
### Bug description

Spotify songs are not stable, some of them are working and others are not in the new update of lavamusic.

### Step to reproduce

when i add someWhen I add some Spotify songs, some of them work and others do not, He just added it to the queue but it didn't start to work, but they are not generally stable

### Operating system

Windows

### Nodejs version

>=18

**Comment by NotSoMik** [comment]
Does this handler support sub commands since I keep getting error when I use them

**Comment by REMOOO** [comment]
> 

i just using prefix command.

**Comment by REMOOO** [comment]
@brblacky

**Comment by zoli456** [comment]
Remove the Spotify support from the bot and install **LavaSrc** plugin to Lavalink.
[https://github.com/TopiSenpai/LavaSrc](url)
