### ISSUE TITLE
Dj Not Working

### ISSUE THREAD

**Issue by CoolMusic1** [brblacky/lavamusic#406]
### Bug description

Dj Not working 

### Step to reproduce

Dj not working

### Operating system

Linux

### Nodejs version

v18

### Errors / Logs

Dj not working

**Comment by PixelHir** [comment]
ok, and?

**Comment by StarnightFox** [comment]
Please provide steps for what you did and what your actual error is. None of us can help you if you just say "bot no work"

**Comment by LucasB25** [comment]
#403
