### ISSUE TITLE
Apple Music won't work

### ISSUE THREAD

**Issue by CoolMusic1** [brblacky/lavamusic#410]
### Bug description

apple music is not working

### Step to reproduce

```/play https://music.apple.com/us/album/kesariya-from-brahmastra/1635013814?i=1635014240```

### Operating system

Linux

### Nodejs version

v18

### Errors / Logs

There was an error while searching: Cannot read properties of null (reading 'data')

**Comment by StarnightFox** [comment]
as far as i know, lavalink doesnt support apple music unless you actually tell it to with a plugin, which youd need to add to the bot and possible the lavalink node (although i may be a little bit off with this last bit). You'd also most likely need to give it an api key too

**Comment by zoli456** [comment]
Install **LavaSrc** plugin to **Lavalink**.
[https://github.com/TopiSenpai/LavaSrc](https://github.com/brblacky/lavamusic/issues/url)
