### ISSUE TITLE
Add command to both /shuffle and /play a playlist

### ISSUE THREAD

**Issue by catalinberta** [brblacky/lavamusic#411]
### Description of your suggestion

At the moment, when a playlist is /played, all songs are in the original order of the playlist.
This is not ideal considering most playlist have a lot of songs and you'd always listen to the first ones, probably never reach the end :-)

The current solution is to manually /shuffle the playlist every time. Would be nice to have one command that does both.
Personally, I find that the default behavior of /play should be shuffled (like on YouTube Music). But I leave that to you.
I guess another solution is to have a new command /shuffleplay maybe?

Obviously, this a nice to have :)

Looking forward to your feedback

**Comment by StarnightFox** [comment]
tbf, it isnt very hard to implement, depending if youre on the shoukaku or erela.js version 

for erela.js just add `player.queue.shuffle()`
for shoukaku its just `player.setShuffle(true)`

This is what i did in my my own coded bot (using modified shoukaku), and from a quick testing it worked in lavamusic for me too

**Comment by LucasB25** [comment]
#403
