### ISSUE TITLE
Bot needs admin privileges to work

### ISSUE THREAD

**Issue by alez007** [brblacky/lavamusic#412]
### Bug description

For some reason the bot needs administrator permissions to work. Briefly looking over the commands in the code, it should need just a few permissions: View Channels, Send Messages, Embed Links, Use Application Commands, Connect, Speak 

Might be wrong but whatever I try, anything less than administrator permissions will not play anything or join the music channel.

### Step to reproduce

1. go to https://discordapi.com/permissions.html
2. select permissions: View Channels, Send Messages, Embed Links, Add Reactions, Use Application Commands, Connect, Speak
3. invite the bot
4. try to play something

### Operating system

linux

### Nodejs version

docker version from master branch

### Errors / Logs

`I don't have enough permissions connect your VC! Please give me permission to CONNECT or SPEAK.`

**Comment by LucasB25** [comment]
client: ['SendMessages', 'ViewChannel', 'EmbedLinks', 'Connect', 'Speak'],

**Comment by alez007** [comment]
> ```
>             client: ['SendMessages', 'ViewChannel', 'EmbedLinks', 'Connect', 'Speak'],
> ```

is this a configuration thing I need to add ?

**Comment by LucasB25** [comment]
no you must have put your leave wrong

**Comment by alez007** [comment]
> no you must have put your leave wrong

Sorry I'm not following can you please give me more information? I'm not very versed in discord api

**Comment by Suhaybu** [comment]
I think this might have to do with your permission of your voice channel itself, make sure the permissions of the channel don't interfere with the bot's permissions.

This surely is a problem associated to how your discord server is configured and not the bot itself. Check the roles and permissions the bot has.

**Comment by alez007** [comment]
> I think this might have to do with your permission of your voice channel itself, make sure the permissions of the channel don't interfere with the bot's permissions.
> 
> This surely is a problem associated to how your discord server is configured and not the bot itself. Check the roles and permissions the bot has.

this is the right answer, my music channel didn't give the right permissions for the role the bot was using, thanks!
