### ISSUE TITLE
Not playing music directly from spotify

### ISSUE THREAD

**Issue by thac-01** [brblacky/lavamusic#42]
in the latest changes it should play music directly from spotify... but it doesn't work, it always plays music from youtube modifying the message sent with the spotify metadata

**Comment by brblacky** [comment]
No

**Comment by brblacky** [comment]
U can't find this music in youtube Use this link and see where is playing https://open.spotify.com/track/608egEwtCpDqB5itjrEmHt?si

**Comment by SoulHunter287** [comment]
> in the latest changes it should play music directly from spotify... but it doesn't work, it always plays music from youtube modifying the message sent with the spotify metadata

it plays music from spotify if u provide the link to the song/playlist 
sometimes it will play the songs from youtube if the bot finds the same song on youtube even if you provide the link
