### ISSUE TITLE
The Pause button is not working properly.

### ISSUE THREAD

**Issue by WolverStones** [brblacky/lavamusic#426]
https://github.com/brblacky/lavamusic/blob/main/src/events/player/TrackStart.ts#L21

The button should change depending on whether the song is paused or playing, but unfortunately the 'Pause' text is still displayed after pausing.

**Comment by WolverStones** [comment]
![m8eIMMf](https://user-images.githubusercontent.com/7571437/225177328-3b9b0c3e-abfd-4d72-9d27-540af8d5b82b.png)
![AtoyoIO](https://user-images.githubusercontent.com/7571437/225177468-809eeab3-afbe-4c3a-92f2-431510831683.png)

**Comment by StarnightFox** [comment]
Hey, sorry that it's taken so long. This is fixed in #436

**Comment by BallavaNarayan** [comment]
@StarnightFox is it possible to update the Buttons if we use Pause or Resume Command as well

**Comment by StarnightFox** [comment]
> @StarnightFox is it possible to update the Buttons if we use Pause or Resume Command as well 

Technically yes. Although it would require at the very least caching the message ID of the track start message and then checking if it still exists first, and then editing it. Which isn't too big of a pain to do, although for big bots it's gonna add a decent chunk of ram usage depending on how many players there are, especially if you want to cache more than just the message ID
