### ISSUE TITLE
[Suggestion] Use better-erela.js-spotify instead of Lavasfy.

### ISSUE THREAD

**Issue by getxd-dev** [brblacky/lavamusic#43]
**Is your feature request related to a problem? Please describe.**
Some Spotify playlists, album and track don't work with Lavasfy.

**Describe the solution you'd like**
Use [better-erela.js-spotify](https://github.com/NezuChan/better-erela.js-spotify) instead of Lavasfy. It's more better than Lavasfy.

**Comment by brblacky** [comment]
Ok I will try
