### ISSUE TITLE
Startup bot get killed

### ISSUE THREAD

**Issue by HusseinAhmed2** [brblacky/lavamusic#433]
When i run the bot i get this can someone help please

container@pterodactyl~ Server marked as running...
:/home/container$ ${STARTUP_COMMAND}
> lavamusic@3.1.0 start
> npm run start:bot
> lavamusic@3.1.0 start:bot
> npm run build && node --enable-source-maps dist/index.js
> lavamusic@3.1.0 build
> tsc --project tsconfig.json
Killed
container@pterodactyl~ Server marked as offline...

**Comment by WolverStones** [comment]
What version of node are you using? The requirement is node 17.

**Comment by HusseinAhmed2** [comment]
I’m using node 18 already
