### ISSUE TITLE
2 Errors

### ISSUE THREAD

**Issue by CoolioTT** [brblacky/lavamusic#443]
![image](https://user-images.githubusercontent.com/110967917/232254312-9684edaa-0f4c-41b7-849f-7b8c6dd82727.png)
 One error is when I typed /help and the other is /play

**Comment by WolverStones** [comment]
You need to have a node connected (lavalink server) you can use your own which you will host together with the bot or find a public one and use that. But without a lavalink server the bot won't work.

**Comment by CoolioTT** [comment]
i have it hosted on the same vps as the bot

**Comment by WolverStones** [comment]
Are you sure that the bot will connect to the Lavalink server? Do you have the correct version of Lavalink? Version 3.3.2.3 or higher is required.

**Comment by CoolioTT** [comment]
I have lavalink 3.7.5

**Comment by brblacky** [comment]
> ![image](https://user-images.githubusercontent.com/110967917/232254312-9684edaa-0f4c-41b7-849f-7b8c6dd82727.png) One error is when I typed /help and the other is /play

Your lavalink don't connect with bot
