### ISSUE TITLE
Getting error when using commands

### ISSUE THREAD

**Issue by Amalbro07** [brblacky/lavamusic#446]
![Screenshot_2023-04-18-18-57-35-69_dce875ef40efa4e902b2719365b6f678.jpg](https://user-images.githubusercontent.com/124343610/232799519-bae2b4bb-e01d-4b8e-a5d5-5c745fd2a02d.jpg)

An error occured: `Error: 
Invalid `prisma.guild.findUnique()` invocation:

libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by Amalbro07** [comment]
> In the .env file, simply replace 'this' with your connection string 
> 
> ```
> DATABASE_URL="mongodb+srv://Blacky:xxxxxxxxxxxx" # Your MongoDB URL
> ```

An error occured: `Error: 
Invalid `prisma.guild.findUnique()` invocation:


Raw query failed. Code: `unknown`. Message: `Command failed (AtlasError): empty database name not allowed
	at 18430f5589521423205c84920ac589be/atlasproxy/session_proxy.go:702
	at 18430f5589521423205c84920ac589be/atlasproxy/session_proxy.go:1746
	at 18430f5589521423205c84920ac589be/atlasproxy/session_proxy.go:1163
	at mongodb/mongonet@v0.0.0-20230203202515-6c9dabc93327/proxy_session.go:367
	at mongodb/mongonet@v0.0.0-20230203202515-6c9dabc93327/proxy_session.go:128
	at mongodb/mongonet@v0.0.0-20230203202515-6c9dabc93327/session.go:188
	at mongodb/mongonet@v0.0.0-20230203202515-6c9dabc93327/server.go:280
	at src/runtime/asm_arm64.s:1172)``

**Comment by Amalbro07** [comment]
> In the .env file, simply replace 'this' with your connection string 
> 
> ```
> DATABASE_URL="mongodb+srv://Blacky:xxxxxxxxxxxx" # Your MongoDB URL
> ```

mongodb+srv://username:password@cluster0.lghcp.mongodb.net/?retryWrites=true&w=majority

Is this the correct format?

**Comment by WolverStones** [comment]
Yes, Of course, you need to replace the username and password with the correct credentials. However, an important step is to generate the Prisma client:

If you're using Replit, follow these instructions:

```Go to prisma/schema.prisma and add the engine type like this:

  provider = "prisma-client-js"
  engineType = "binary"
}```

2. Then run this command:

```npx prisma generate```

3. Finally, you can run the bot with either of these commands:

```npm run start``` or ```npm start```
