### ISSUE TITLE
mongoose 

### ISSUE THREAD

**Issue by AbelCode1** [brblacky/lavamusic#45]
problem 1

MongooseError: Operation `prefixes.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:149:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by AbelCode1** [comment]
ugh one problem after the next

when i try to use a command it dont work i use slash commands it say this interaction failed

**Comment by SoulHunter287** [comment]
> problem 1
> 
> MongooseError: Operation `prefixes.findOne()` buffering timed out after 10000ms at Timeout. (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:149:23) at listOnTimeout (node:internal/timers:557:17) at processTimers (node:internal/timers:500:7)

 this happens when your database is not connected, Try checking out following things -

*Is you database connected and you are pointing to the same url from your code.
*check if your mongoose.connect(...) code is loading.
