### ISSUE TITLE
Support for Handling Spotify URL

### ISSUE THREAD

**Issue by neptalu0** [brblacky/lavamusic#450]
I think some were able to do that to just convert track/playlist URLs and search them off youtube. Should require App credentials like ID and Secret

**Comment by WolverStones** [comment]
> I think some were able to do that to just convert track/playlist URLs and search them off youtube. Should require App credentials like ID and Secret


Just download the Lavalink plugin, which requires LavaLink version 3.6.x. More information can be found here: https://github.com/TopiSenpai/LavaSrc
