### ISSUE TITLE
An error occured: `Error:  Invalid `prisma.guild.findUnique()` invocation:

### ISSUE THREAD

**Issue by HellNoNium** [brblacky/lavamusic#451]
An error occured: `Error: 
Invalid `prisma.guild.findUnique()` invocation:

Raw query failed. Code: `unknown`. Message: `Command failed (AtlasError): empty database name not allowed
	at e2b7920a53d244485a2d909a16cec1a7/atlasproxy/session_proxy.go:702
	at e2b7920a53d244485a2d909a16cec1a7/atlasproxy/session_proxy.go:1746
	at e2b7920a53d244485a2d909a16cec1a7/atlasproxy/session_proxy.go:1163
	at mongodb/mongonet@v0.0.0-20230203202515-6c9dabc93327/proxy_session.go:367
	at mongodb/mongonet@v0.0.0-20230203202515-6c9dabc93327/proxy_session.go:128
	at mongodb/mongonet@v0.0.0-20230203202515-6c9dabc93327/session.go:188
	at mongodb/mongonet@v0.0.0-20230203202515-6c9dabc93327/server.go:280
	at src/runtime/asm_amd64.s:1594)``

**Comment by HellNoNium** [comment]
Please fix it.

**Comment by UnpoeticSir** [comment]
Same like you

**Comment by Beps-s** [comment]
ensure that your db url has a dbname in it.
like so:

mongodb+srv://username:password@cluster.mongodb.net/dbname?retryWrites=true&w=majority
