### ISSUE TITLE
An error has occurred : TypeError: fetch failed

### ISSUE THREAD

**Issue by liloko** [brblacky/lavamusic#467]
![image](https://github.com/brblacky/lavamusic/assets/78354559/92dd8e44-8045-4984-bede-333fc6de97dd)
how to fix this?

**Comment by Fyphen1223** [comment]
It seems that your network is the cause of the problem. Did you try re-start or something?

**Comment by Fyphen1223** [comment]
or you might made typo of your lavalink address.
