### ISSUE TITLE
Syntax Error on Start

### ISSUE THREAD

**Issue by EliRickard** [brblacky/lavamusic#47]
**Describe the bug**
Bot Won't Start

**To Reproduce**
N/A

**Expected behavior**
The bot would start without a syntax error.

**Screenshots**
<img width="727" alt="Screen Shot 2021-11-28 at 1 36 38 pm" src="https://user-images.githubusercontent.com/38917063/143726712-4f40d021-fd7a-4070-bed2-bcd9d88d60c4.png">

**Additional context**
It may be worth noting that several commands have been disabled by the use of appending the files with .off

**Comment by EliRickard** [comment]
The error was a missing comma after the description in several slash command files. This should be fixed.

**Comment by brblacky** [comment]
Fixed
