### ISSUE TITLE
`/setup` and `/prefix` commands produce similar errors

### ISSUE THREAD

**Issue by Thisisauser6443** [brblacky/lavamusic#482]
I'm not entirely sure what's going on here. Permissions seem fine, and I was able to reproduce the error from v4 and the latest commit, at the time of writing:

![image](https://github.com/brblacky/lavamusic/assets/75092921/4126bf74-9cf4-40b2-ac18-d4e63e50de00)

(I'm not sure on what other info I'll need to provide, as well, so if there's something missing, just let me know)

**Comment by jasonmidul** [comment]
When comes error?? On start or command?

**Comment by Thisisauser6443** [comment]
When I actually run the command
