### ISSUE TITLE
Discord use App Commands Do not Work

### ISSUE THREAD

**Issue by houseofbugs** [brblacky/lavamusic#485]
When using the Discord use app / commands it doesn't work at all. Using the prefix works as expected.

![image](https://github.com/brblacky/lavamusic/assets/25088191/336682f1-7932-4e97-85e7-da7953b7bcfa)

**Comment by brblacky** [comment]
Where are you hosting ?

**Comment by houseofbugs** [comment]
Docker on my own server here.

**Comment by brblacky** [comment]
It is only about cmd issue ?

**Comment by houseofbugs** [comment]
Correct

**Comment by brblacky** [comment]
try new code
