### ISSUE TITLE
error in playerMove.js

### ISSUE THREAD

**Issue by lolpoe** [brblacky/lavamusic#49]
**Describe the bug**
data:    index.js:16886 - [29-11-2021 06:46:47]: [LOG] Player has been destroyed in 890983793622667274
data:    index.js:16886 - ReferenceError: message is not defined
data:    index.js:16886 -     at module.exports (/root/og/src/events/Lavalink/playerMove.js:6:9)
data:    index.js:16886 -     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**To Reproduce**
1.Play a song
2. Manually disconnect bot

**Expected behavior**
Send "Music stopped as I have been disconnected from the voice channel." message in player channel.

**Comment by lolpoe** [comment]
also was having a issue like [#29](https://github.com/brblacky/lavamusic/issues/29) 
the bot was stuck on 0 seconds and i couldnt control it. it said it was in a vc but it wasn't.

**Comment by brblacky** [comment]
Fixed https://github.com/brblacky/lavamusic/commit/9af279be486c517c1c36abccf6511c119b657f50
