### ISSUE TITLE
no exported member

### ISSUE THREAD

**Issue by 5wi5wi** [brblacky/lavamusic#499]
idk what to do (  error TS2305 )

> lavamusic@4.0.4 start
> npm run build && node dist/index.js

> lavamusic@4.0.4 build
> tsc --project tsconfig.json

src/database/server.ts:1:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Guild'.

1 import { Guild, PrismaClient } from '@prisma/client';
           ~~~~~

src/database/user.ts:1:24 - error TS2305: Module '"@prisma/client"' has no exported member 'User'.

1 import { PrismaClient, User } from '@prisma/client';
                         ~~~~


Found 2 errors in 2 files.

Errors  Files
     1  src/database/server.ts:1
     1  src/database/user.ts:1

**Comment by LucasB25** [comment]
update code
