### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by mercenaryexc** [brblacky/lavamusic#5]
![unknown](https://user-images.githubusercontent.com/81456012/130212199-ef914709-249d-4896-96c5-463a8fac42ba.png)

**Comment by brblacky** [comment]
This is only work in discord .js v 12

**Comment by mercenaryexc** [comment]
i use discord js 12.5.3

**Comment by brblacky** [comment]
Turn on Privileged Gateway Intents in your Discord developer portal

**Comment by brblacky** [comment]
Turn on Privileged Gateway Intents in your Discord developer portal

**Comment by mercenaryexc** [comment]
![asa](https://user-images.githubusercontent.com/81456012/130299373-16a30d82-b666-45f9-a37a-a88612ed8ca6.png)
I run on rdp but error

**Comment by brblacky** [comment]
Install node v 16 please read requirements

**Comment by mercenaryexc** [comment]
![qq](https://user-images.githubusercontent.com/81456012/130334867-a85d6991-d2be-4132-a7a6-e1d06ba840c5.png)
why eror   ? help

**Comment by brblacky** [comment]
This is your lavalink server error
