### ISSUE TITLE
Playlist not working

### ISSUE THREAD

**Issue by delidolu1adam** [brblacky/lavamusic#501]
The bot does not support playlists like this. Can you please give this?

Example playlist: https://www.youtube.com/watch?v=djkk8CUoVOo&list=PLpUWVFi6U7UYbk0mscwTfN1jcsu7fTp2d

**Comment by Guazy** [comment]
![lavamusic-error](https://github.com/brblacky/lavamusic/assets/6446405/7b132077-a558-472b-88b2-d7c6570b2bc5)

**Comment by hikeri** [comment]
Either this has been fixed, or you have problems with Lavalink. Because everything works for me.
