### ISSUE TITLE
Bot joins the channel and leaves immediately

### ISSUE THREAD

**Issue by delidolu1adam** [brblacky/lavamusic#504]
I filled in all the required information correctly. Even though I checked everything again, I couldn't find any problems. However, when I use a command for the bot, the bot joins the channel and leaves the channel immediately.

![lavamusic-error](https://github.com/brblacky/lavamusic/assets/6446405/42963a36-70a4-49f3-89e2-893882457ff8)

**Comment by delidolu1adam** [comment]
/join or /play comman error.

An error occurred: Error: Can't find any nodes to connect on.

@brblacky

**Comment by brblacky** [comment]
Your node is not connected
