### ISSUE TITLE
Bot is not starting cause many files are not under root

### ISSUE THREAD

**Issue by zynkclout** [brblacky/lavamusic#506]
/lavamusic/lavamusic/src/plugin/plugins/antiCrash.ts' is not under 'rootDir' '/home/lavamusic/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'

error TS6059: File '/home/lavamusic/lavamusic/src/plugin/plugins/keepAlive.ts' is not under 'rootDir' '/home/lavamusic/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'

error TS6059: File '/home/lavamusic/lavamusic/src/plugin/plugins/updateStatus.ts' is not under 'rootDir' '/home/lavamusic/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'

Found 65 errors.

npm ERR! code 2
npm ERR! path /home/lavamusic
npm ERR! command failed
npm ERR! command sh -c npm run build && node dist/index.js

**Comment by brblacky** [comment]
Fixed
