### ISSUE TITLE
Offical bot is not working

### ISSUE THREAD

**Issue by delidolu1adam** [brblacky/lavamusic#507]
I added your bot to my discord server, but no commands are working. I downloaded the source files and tried to run it on localhost, but the same problem persists there. Could you please fix the problem? Thanks. @brblacky 

ERROR CODE: An error occurred: Error: Can't find any nodes to connect on

----- CHAT GPT -----
It indicates that this error is caused by a connection issue with your Discord bot. The "Can't find any nodes to connect on" error likely indicates that there is a problem connecting to the Discord API. To solve this problem, you can follow these steps:

Token Check: Make sure that your bot's token that you received from the Discord Developer Portal is set correctly. The token allows your bot to communicate with Discord servers. You may receive a connection error when the wrong token is given.

Library Version: Check the Discord library version you are using. If the library is an old version, it may be incompatible with updates to the Discord API, causing you to receive connection errors. You may need to update your library version.

Code Error: There may be an error in your bot's code. Review the block of code that allows your bot to connect with the Discord API and check for any errors or omissions.

API Status: There may be a connection problem due to an issue with the Discord API. You can check if there are any outages in the Discord API by checking Discord's status page. If there is an outage, you can't do anything but wait.

Server Problems: The server where your bot is hosted may have network or system problems. Check the server's connections and contact your server provider to troubleshoot connection problems.

By following the steps above, you can solve the "Can't find any nodes to connect on" error in your Discord bot.

**Comment by 0x6DD8** [comment]
Just docker composed it and have same problem

**Comment by brblacky** [comment]
Ok let me check

**Comment by LucasB25** [comment]
Your concern comes from home and not from the code
