### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by AbelCode1** [brblacky/lavamusic#54]
![C55641A1-5557-47F6-8001-F55A8BD1087E](https://user-images.githubusercontent.com/90580222/144223493-cce2ee0e-934c-4f34-9358-1421baad5c19.jpeg)

**Comment by brblacky** [comment]
It is fixed https://github.com/brblacky/lavamusic/commit/16ffe229ad3f0dca6fe39995b1fd7a3741c76b89
