### ISSUE TITLE
/help does not work in direct messages - An unexcepted error occured.

### ISSUE THREAD

**Issue by StefanLobbenmeier** [brblacky/lavamusic#56]
**Describe the bug**
/help does not work in direct messages

**To Reproduce**
1. Send the bot a direct message /help
2. It responds with An unexcepted error occured.

**Expected behavior**
Help is printed :)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Discord Client
 - Version Stable 106905 (1eb8c0f) Host 0.0.16

**Additional context**
TypeError: Cannot read properties of null (reading 'user') at Object.run (/home/stefan/musicbot-lavalink/lavamusic/src/slashCommands/Information/help.js:19:54) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async module.exports (/home/stefan/musicbot-lavalink/lavamusic/src/events/Client/interactionCreate.js:41:13) {stack: "TypeError: Cannot read properties of null (reading…sic/src/events/Client/interactionCreate.js:41:13)", message: "Cannot read properties of null (reading 'user')"}

The issue seems to be interaction.member being null in https://github.com/brblacky/lavamusic/blob/f8641cc06f4301545c491f4a03e8e5a249599b75/src/slashCommands/Information/help.js#L17

**Comment by brblacky** [comment]
If you need not can be send help command than change in messageCrate.js
