### ISSUE TITLE
How do I make a MongoDB?

### ISSUE THREAD

**Issue by MaxGamer637** [brblacky/lavamusic#59]
Hi, I wanted to use the code, but i need a MongoDB_url, how I make one?

**Comment by brblacky** [comment]
Readme

**Comment by KayTwenty** [comment]
You can create a free cluster, when you create a cluster, there should be a "connect" button on the right. When you click on the connect button, you'll be greeted with three options. Press "connect your application", and then copy the written code at the bottom. When copied make sure to type the password to your cluster in the <password>.
