### ISSUE TITLE
hold on im getting info

### ISSUE THREAD

**Issue by AbelCode1** [brblacky/lavamusic#64]
![DD1998C7-BBA9-4479-BE40-979BE1EB9C04](https://user-images.githubusercontent.com/90580222/146180009-b10c7834-e7ef-465a-8dd7-e5e206bcbb29.jpeg)

**Comment by JKirito** [comment]
That should be an import/export problem. The only reason it will find Client2 as undefined is either it is not defined or there is some problem while importing. Check the Import statement. This should be fixed by it then.

**Comment by AbelCode1** [comment]
> That should be an import/export problem. The only reason it will find Client2 as undefined is either it is not defined or there is some problem while importing. Check the Import statement. This should be fixed by it then.

![E1BD5F4E-474B-4907-8496-21E82F64B7FD](https://user-images.githubusercontent.com/90580222/146188272-12255a3e-db59-47a2-97e1-9497135aaf6d.jpeg)

**Comment by AbelCode1** [comment]
> That should be an import/export problem. The only reason it will find Client2 as undefined is either it is not defined or there is some problem while importing. Check the Import statement. This should be fixed by it then.

![Uploading 9CA61C09-8899-4223-94F0-F3F570A98F29.jpeg…]()

**Comment by AbelCode1** [comment]
> That should be an import/export problem. The only reason it will find Client2 as undefined is either it is not defined or there is some problem while importing. Check the Import statement. This should be fixed by it then.

![C26877EC-802C-421B-B73D-FAC17AE8E1A6](https://user-images.githubusercontent.com/90580222/146188794-bcc9ef54-b398-41e0-b5a2-066447318f8b.jpeg)

**Comment by AbelCode1** [comment]
> That should be an import/export problem. The only reason it will find Client2 as undefined is either it is not defined or there is some problem while importing. Check the Import statement. This should be fixed by it then.

I fixed the error but there is a new one
![983A6697-2682-4E68-9ECA-B94E8A1D2C2A](https://user-images.githubusercontent.com/90580222/146192928-1a8bf0cb-4bde-46e3-84de-00f150a5c903.jpeg)

**Comment by AbelCode1** [comment]
intents are on in discord dev portal

![65D3FE2F-4508-42B5-8FD0-927EACC1B921](https://user-images.githubusercontent.com/90580222/146193031-7e2ce36d-85d2-4589-aa16-aba6402990c2.jpeg)

**Comment by AbelCode1** [comment]
![AFC45EE3-469E-4954-B3C9-F9D2DABA271B](https://user-images.githubusercontent.com/90580222/146275593-37577860-9f62-4a21-93f1-44a7f0bb5e7e.jpeg)

**Comment by AbelCode1** [comment]
![56713E26-112C-43B0-8A2E-E7780B33CCBF](https://user-images.githubusercontent.com/90580222/146275921-8de9e7e8-d2c1-4ed5-8077-fa1d5d0b7cd8.jpeg)
![7610AAE8-2457-4CF6-A56E-3BF24BA48F7D](https://user-images.githubusercontent.com/90580222/146275940-51c1d0b2-db0d-453e-a8d8-04b0bb4261e1.jpeg)
![6819ECA8-9342-4458-ACF7-CA568E95CB6A](https://user-images.githubusercontent.com/90580222/146275970-0648de69-8b62-4bbf-96af-af78ab004028.jpeg)
![36E125ED-E22A-49A4-A1B2-D211FEE68A93](https://user-images.githubusercontent.com/90580222/146275996-a1de1fe7-42af-4f06-99e5-0a0959225924.jpeg)
![1F91631C-D3FC-4A56-8ED3-CD7840D365A7](https://user-images.githubusercontent.com/90580222/146276015-9c357f8e-19fe-4236-b932-232015db9eca.jpeg)
![562EBCF4-62C3-43B0-B7AD-F88E8E66FD71](https://user-images.githubusercontent.com/90580222/146276035-1cae169a-b7ee-4993-ab52-e81b01befac3.jpeg)

**Comment by AbelCode1** [comment]
Nvm
