### ISSUE TITLE
32 bit integer

### ISSUE THREAD

**Issue by AbelCode1** [brblacky/lavamusic#68]
node:19054) TimeoutOverflowWarning: 9223372036854776000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by alez007** [comment]
this same problem happened to me twice today, any ideas what's causing this ?

**Comment by NotAditya69** [comment]
you are assigning a timer that is not a 32 bit integer

**Comment by alez007** [comment]
> you are assigning a timer that is not a 32 bit integer

I am definitely not :) but the code might haha, any reason why it could react that point ?
