### ISSUE TITLE
Add multiple lavalink

### ISSUE THREAD

**Issue by Hjgaming** [brblacky/lavamusic#76]
• add multiple lavalink server support
• add more command 
• add dropdown help menu

**Comment by hypwreck1** [comment]
just change this line

```
nodes: [
        {
          identifier: this.config.nodes.id,
          host: this.config.nodes.host,
          port: this.config.nodes.port,
          password: this.config.nodes.password,
          secure: this.config.nodes.secure,
        },
      ],
```
      
   to `nodes: this.config.nodes,` and after you can add multiples lavalink

**Comment by hypwreck1** [comment]
this is how to set multiples lavalink on config.js file

```
nodes: [
    {

      host: "host",
      id: "id",
      port: port,
      password: "pass",
      secure: false

    },
    {

      host: "host",
      id: "id",
      port: port,
      password: "pass",
      secure: false

    },
    {

      host: "host",
      id: "id",
      port: port,
      password: "pass",
      secure: false
          
    },
  ],
```

**Comment by brblacky** [comment]
> just change this line
> 
> ```
> nodes: [
>         {
>           identifier: this.config.nodes.id,
>           host: this.config.nodes.host,
>           port: this.config.nodes.port,
>           password: this.config.nodes.password,
>           secure: this.config.nodes.secure,
>         },
>       ],
> ```
> 
> to `nodes: this.config.nodes,` and after that you can add multiples lavalink

Not work like this

**Comment by hypwreck1** [comment]
> > just change this line
> > ```
> > nodes: [
> >         {
> >           identifier: this.config.nodes.id,
> >           host: this.config.nodes.host,
> >           port: this.config.nodes.port,
> >           password: this.config.nodes.password,
> >           secure: this.config.nodes.secure,
> >         },
> >       ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to `nodes: this.config.nodes,` and after that you can add multiples lavalink
> 
> Not work like this

it  works with me

**Comment by brblacky** [comment]
change in `MusicClient.js`
```js
nodes: [
        {
          identifier: this.config.nodes.id[0],
          host: this.config.nodes.host[0],
          port: this.config.nodes.port[0],
          password: this.config.nodes.password[0],
          secure: this.config.nodes.secure[0],
        },
        {
          identifier: this.config.nodes.id[1],
          host: this.config.nodes.host[1],
          port: this.config.nodes.port[1],
          password: this.config.nodes.password[1],
          secure: this.config.nodes.secure[1],
        },
      ],
```

**Comment by brblacky** [comment]
> > > just change this line
> > > ```
> > > nodes: [
> > >         {
> > >           identifier: this.config.nodes.id,
> > >           host: this.config.nodes.host,
> > >           port: this.config.nodes.port,
> > >           password: this.config.nodes.password,
> > >           secure: this.config.nodes.secure,
> > >         },
> > >       ],
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to `nodes: this.config.nodes,` and after that you can add multiples lavalink
> > 
> > 
> > Not work like this
> 
> it works with me

But lavasfy how to connect that ?

**Comment by hypwreck1** [comment]
> > > > just change this line
> > > > ```
> > > > nodes: [
> > > >         {
> > > >           identifier: this.config.nodes.id,
> > > >           host: this.config.nodes.host,
> > > >           port: this.config.nodes.port,
> > > >           password: this.config.nodes.password,
> > > >           secure: this.config.nodes.secure,
> > > >         },
> > > >       ],
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > to `nodes: this.config.nodes,` and after that you can add multiples lavalink
> > > 
> > > 
> > > Not work like this
> > 
> > 
> > it works with me
> 
> But lavasfy how to connect that ?

i dont change anything to lavasfy
![Screenshot 2022-01-03 200132](https://user-images.githubusercontent.com/90232327/147928295-2ecc80f7-d814-4181-a3b9-9222a5df1699.png)
so as you can see here i set 3 lavalinks and all of them is connected also i already test if one of the lavalink is down it will auto connect to other lavalink

just leave lavasfy

**Comment by brblacky** [comment]
Play Spotify url

**Comment by hypwreck1** [comment]
> Play Spotify url

yea i realized it doesnt work if you use spotify url, but theres other way how to make it works, you can try better-erela.js-spotify package, here the link: https://www.npmjs.com/package/better-erela.js-spotify but the other problem is you have to make a lot of changes to the codes since you need to remove lavasfy and make a new play command. you can dm me and ill help you here my discord id: ɯnɔ#5230

**Comment by hypwreck1** [comment]
i also recommend you to switch from lavasfy better-erela.js-spotify since it doesnt used spotify api key and the search is more accurate

**Comment by brblacky** [comment]
> > Play Spotify url
> 
> yea i realized it doesnt work if you use spotify url, but theres other way how to make it works, you can try better-erela.js-spotify package, here the link: https://www.npmjs.com/package/better-erela.js-spotify but the other problem is you have to make a lot of changes to the codes since you need to remove lavasfy and make a new play command. you can dm me and ill help you here my discord id: ɯnɔ#5230

Thanks  but I can do

**Comment by IcyDiscord** [comment]
> > > > > just change this line
> > > > > ```
> > > > > nodes: [
> > > > >         {
> > > > >           identifier: this.config.nodes.id,
> > > > >           host: this.config.nodes.host,
> > > > >           port: this.config.nodes.port,
> > > > >           password: this.config.nodes.password,
> > > > >           secure: this.config.nodes.secure,
> > > > >         },
> > > > >       ],
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > to `nodes: this.config.nodes,` and after that you can add multiples lavalink
> > > > 
> > > > 
> > > > Not work like this
> > > 
> > > 
> > > it works with me
> > 
> > 
> > But lavasfy how to connect that ?
> 
> i dont change anything to lavasfy ![Screenshot 2022-01-03 200132](https://user-images.githubusercontent.com/90232327/147928295-2ecc80f7-d814-4181-a3b9-9222a5df1699.png) so as you can see here i set 3 lavalinks and all of them is connected also i already test if one of the lavalink is down it will auto connect to other lavalink

how did u make lavalink in falixnodes?
