### ISSUE TITLE
Join a voice channel and queue songs by name/url.

### ISSUE THREAD

**Issue by lia1324** [brblacky/lavamusic#77]
![image](https://user-images.githubusercontent.com/96490782/148034080-5d79309d-c9f6-42e3-a639-762d2580e779.png)

**Comment by getxd-dev** [comment]
?

**Comment by jerry-619** [comment]
he saying make setup command like this

**Comment by TEDDY6969** [comment]
If ya guys want a setup command then vote for it in the polls at our support server. 
[Link to the poll](https://discord.gg/MZdFtYNV2t)

**Comment by LucasB25** [comment]
@brblacky I see the concern seems to have been resolved, so you can close
