### ISSUE TITLE
I got a Mongo error

### ISSUE THREAD

**Issue by omxpro** [brblacky/lavamusic#79]
**Describe the bug**

**To Reproduce**
1. Go to 'a hosting provider that uses pterodactyl software'
2. Click on 'make a account'
3. Scroll down to 'your server and git clone the repo and run npm install and then run node . (Make sure to fill in .env'

**Expected behavior**
I expected it to start normally

**Screenshots**
![Screenshot_20220107-102418_Brave](https://user-images.githubusercontent.com/69719569/148497684-0d2f4584-8328-46c5-b173-d0fb66ea6382.png)
![Screenshot_20220107-101039_Brave](https://user-images.githubusercontent.com/69719569/148497688-c14f38f4-576c-4270-a753-84bb54107506.png)

**Desktop (please complete the following information):**
 - OS: Debain
 - Browser None
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M12
 - OS: Android 11
 - Browser Brave
 - Version latest

**Comment by brblacky** [comment]
Kindly put bot token mongodb url in config.js

**Comment by omxpro** [comment]
mkay
