### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by omxpro** [brblacky/lavamusic#80]
**Is your feature request related to a problem? Please describe.**
this is not like a problem, but whenever there is a new update on github we have to do all the hassle of redoing everything (for selfhosters) so why not make a script or a github action that runs whenever there is a new update and sends data to the bot, the bot will recive the data and recive the added code, and also can you add a `suggest` `vote` and some basic moderation commands like `kick ban mute warn clear warn purge` and also add a command called Execute or exec, it executes the thing you give it like `[prefix]exec npm install discord.py`

**Describe the solution you'd like**
Adding those stuffs

**Comment by AbelCode1** [comment]
> **Is your feature request related to a problem? Please describe.** this is not like a problem, but whenever there is a new update on github we have to do all the hassle of redoing everything (for selfhosters) so why not make a script or a github action that runs whenever there is a new update and sends data to the bot, the bot will recive the data and recive the added code, and also can you add a `suggest` `vote` and some basic moderation commands like `kick ban mute warn clear warn purge` and also add a command called Execute or exec, it executes the thing you give it like `[prefix]exec npm install discord.py`
> 
> **Describe the solution you'd like** Adding those stuffs

Its a music bot 💀

**Comment by getxd-dev** [comment]
> **Is your feature request related to a problem? Please describe.** this is not like a problem, but whenever there is a new update on github we have to do all the hassle of redoing everything (for selfhosters) so why not make a script or a github action that runs whenever there is a new update and sends data to the bot, the bot will recive the data and recive the added code, and also can you add a `suggest` `vote` and some basic moderation commands like `kick ban mute warn clear warn purge` and also add a command called Execute or exec, it executes the thing you give it like `[prefix]exec npm install discord.py`
> 
> **Describe the solution you'd like** Adding those stuffs

wtf, npm install discord.py 💀, I lost brain cells while reading this.

**Comment by omxpro** [comment]
> > **Is your feature request related to a problem? Please describe.** this is not like a problem, but whenever there is a new update on github we have to do all the hassle of redoing everything (for selfhosters) so why not make a script or a github action that runs whenever there is a new update and sends data to the bot, the bot will recive the data and recive the added code, and also can you add a `suggest` `vote` and some basic moderation commands like `kick ban mute warn clear warn purge` and also add a command called Execute or exec, it executes the thing you give it like `[prefix]exec npm install discord.py`
> > **Describe the solution you'd like** Adding those stuffs
> 
> wtf, npm install discord.py 💀, I lost brain cells while reading this.

basically npm of any other commands that you could run through console

**Comment by StefanLobbenmeier** [comment]
> hassle of redoing everything (for selfhosters)

Possibly this gets easier for you if you use the docker image? That way you can either pull the "latest" tag for the latest release or the "main" if you want any change on the main branch (not sure how stable this is, I use latest)

Checkout my sample for this: https://github.com/StefanLobbenmeier/lavamusic-docker-compose
That way docker will check for any update for you.
