### ISSUE TITLE
bot wont accept spotify playlists

### ISSUE THREAD

**Issue by ViraajRandhawa** [brblacky/lavamusic#96]
**Describe the bug**
Whenever me or anybody tries to queue a spotify playlist, the bot simply responds with `Failed To Load Playlist.` or `there were no results found.`
**To Reproduce**

**Expected behavior**
I expected the bot to respond with playing songs from the spotify playlist 

**Screenshots**
![Screenshot 2022-01-20 at 10 58 57 AM](https://user-images.githubusercontent.com/62015795/150279313-699c9688-0918-4480-b0e1-7d991ae105ff.png)
![Screenshot 2022-01-20 at 11 00 27 AM](https://user-images.githubusercontent.com/62015795/150279319-1c99aff0-fc5d-4eaa-8367-2e075290eb6b.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: None
 - Version : Latest version
 -

**Comment by TEDDY6969** [comment]
Hey there,
There might be an error in the Lavalink you are using most probable reason is that your Spotify playlist is private or your lavalink does not support spotify. You should use the lastest version of lavamusic and use a Lavalink which supports the plateform. For further help you can join the support server and can also dm me at ❀SUNSHİNE❀#1359  

I tried to play song from Spotify playlist and it works for me here is an example: 

[Tap to see example](https://media.discordapp.net/attachments/893542491016527973/947503154944147468/Screenshot_2022-02-27-20-00-02-10.png)

**Comment by TGFUKAUSIK** [comment]
It's not cause of lavalink , you haven't installed required package , npm i better-erela Spotify js , then your issue will be fixed , thank me later!
